package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;




/**
 * Adhere generated by hbm2java
 */

public class Adhere  implements java.io.Serializable {


     private long adhereId;
     private String description;

    public Adhere() {
    }

    public Adhere(long adhereId, String description) {
       this.adhereId = adhereId;
       this.description = description;
    }
   
    public long getAdhereId() {
        return this.adhereId;
    }
    
    public void setAdhereId(long adhereId) {
        this.adhereId = adhereId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


