package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Adr generated by hbm2java
 */
public class Adr  implements java.io.Serializable {


     private long adrId;
     private String description;
     private String organ;

    public Adr() {
    }

	
    public Adr(long adrId, String description) {
        this.adrId = adrId;
        this.description = description;
    }
    public Adr(long adrId, String description, String organ) {
       this.adrId = adrId;
       this.description = description;
       this.organ = organ;
    }
   
    public long getAdrId() {
        return this.adrId;
    }
    
    public void setAdrId(long adrId) {
        this.adrId = adrId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getOrgan() {
        return this.organ;
    }
    
    public void setOrgan(String organ) {
        this.organ = organ;
    }




}


