package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Adrhistory generated by hbm2java
 */
public class Adrhistory implements java.io.Serializable {

    private long historyId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private Date dateVisit;
    private String adr;
    private Integer severity;
    private Integer screener;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    public Adrhistory() {
    }

    public Adrhistory(long historyId, Patient patient, long facilityId, Date dateVisit, String adr, Integer severity, Integer screener) {
        this.historyId = historyId;
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.adr = adr;
        this.severity = severity;
        this.screener = screener;
    }

    public Adrhistory(long historyId, Patient patient, long patientId, long facilityId, Date dateVisit, String adr, Integer severity, Integer screener, Date timeStamp, Integer uploaded, Date timeUploaded, String uuid) {
        this.historyId = historyId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.adr = adr;
        this.severity = severity;
        this.screener = screener;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

   
    

    public long getHistoryId() {
        return this.historyId;
    }

    public void setHistoryId(long historyId) {
        this.historyId = historyId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return this.dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public String getAdr() {
        return this.adr;
    }

    public void setAdr(String adr) {
        this.adr = adr;
    }

    public Integer getSeverity() {
        return this.severity;
    }

    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    public Integer getScreener() {
        return this.screener;
    }

    public void setScreener(Integer screener) {
        this.screener = screener;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
