package org.fhi360.lamis.model;
// Generated 11-Jul-2014 10:42:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Anc generated by hbm2java
 */
public class Anc  implements java.io.Serializable {


     private long ancId;
     private Patient patient;
     private long patientId;
     private long facilityId;
     private String ancNum;
     private String uniqueId;
     private Date dateVisit;
     private Date dateEnrolledPmtct;
     private String sourceReferral;
     private Date lmp;
     private Date edd;
     private Integer gestationalAge;
     private Integer gravida;
     private Integer parity;
     private String timeHivDiagnosis;
     private String arvRegimenPast;
     private String arvRegimenCurrent;
     private Date dateArvRegimenCurrent;
     private String syphilisTested;
     private String syphilisTestResult;
     private String syphilisTreated;
     private String hepatitisBTestResult;
     private String hepatitisBTested;
     private String hepatitisCTestResult;
     private String hepatitisCTested;
     private String clinicStage;
     private Date dateConfirmedHiv;
     private Date dateNextAppointment;
     private String funcStatus;
     private Double bodyWeight;
     private Double height;
     private String cd4Ordered;
     private Double cd4;
     private Date timeStamp;
     private Long userId;
     private Integer uploaded;
     private Date timeUploaded;
     private Integer numberAncVisit;
     private Date dateCd4;
     private String viralLoadTestDone;
     private Date dateViralLoad;
     private String viralLoadResult;
      private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    public Anc() {
    }

    public Anc(long ancId, Patient patient, long patientId, long facilityId, String ancNum, String uniqueId, Date dateVisit, Date dateEnrolledPmtct, String sourceReferral, Date lmp, Date edd, Integer gestationalAge, Integer gravida, Integer parity, String timeHivDiagnosis, String arvRegimenPast, String arvRegimenCurrent, Date dateArvRegimenCurrent, String syphilisTested, String syphilisTestResult, String syphilisTreated, String hepatitisBTestResult, String hepatitisBTested, String hepatitisCTestResult, String hepatitisCTested, String clinicStage, Date dateConfirmedHiv, Date dateNextAppointment, String funcStatus, Double bodyWeight, Double height, String cd4Ordered, Double cd4, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, Integer numberAncVisit, Date dateCd4, String viralLoadTestDone, Date dateViralLoad, String viralLoadResult, String uuid) {
        this.ancId = ancId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.ancNum = ancNum;
        this.uniqueId = uniqueId;
        this.dateVisit = dateVisit;
        this.dateEnrolledPmtct = dateEnrolledPmtct;
        this.sourceReferral = sourceReferral;
        this.lmp = lmp;
        this.edd = edd;
        this.gestationalAge = gestationalAge;
        this.gravida = gravida;
        this.parity = parity;
        this.timeHivDiagnosis = timeHivDiagnosis;
        this.arvRegimenPast = arvRegimenPast;
        this.arvRegimenCurrent = arvRegimenCurrent;
        this.dateArvRegimenCurrent = dateArvRegimenCurrent;
        this.syphilisTested = syphilisTested;
        this.syphilisTestResult = syphilisTestResult;
        this.syphilisTreated = syphilisTreated;
        this.hepatitisBTestResult = hepatitisBTestResult;
        this.hepatitisBTested = hepatitisBTested;
        this.hepatitisCTestResult = hepatitisCTestResult;
        this.hepatitisCTested = hepatitisCTested;
        this.clinicStage = clinicStage;
        this.dateConfirmedHiv = dateConfirmedHiv;
        this.dateNextAppointment = dateNextAppointment;
        this.funcStatus = funcStatus;
        this.bodyWeight = bodyWeight;
        this.height = height;
        this.cd4Ordered = cd4Ordered;
        this.cd4 = cd4;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.numberAncVisit = numberAncVisit;
        this.dateCd4 = dateCd4;
        this.viralLoadTestDone = viralLoadTestDone;
        this.dateViralLoad = dateViralLoad;
        this.viralLoadResult = viralLoadResult;
        this.uuid = uuid;
    }


 
    public long getAncId() {
        return ancId;
    }

    public void setAncId(long ancId) {
        this.ancId = ancId;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public String getAncNum() {
        return ancNum;
    }

    public void setAncNum(String ancNum) {
        this.ancNum = ancNum;
    }

    public String getUniqueId() {
        return uniqueId;
    }

    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    public Date getDateVisit() {
        return dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public Date getDateEnrolledPmtct() {
        return dateEnrolledPmtct;
    }

    public void setDateEnrolledPmtct(Date dateEnrolledPmtct) {
        this.dateEnrolledPmtct = dateEnrolledPmtct;
    }

    public String getSourceReferral() {
        return sourceReferral;
    }

    public void setSourceReferral(String sourceReferral) {
        this.sourceReferral = sourceReferral;
    }

    public Date getLmp() {
        return lmp;
    }

    public void setLmp(Date lmp) {
        this.lmp = lmp;
    }

    public Date getEdd() {
        return edd;
    }

    public void setEdd(Date edd) {
        this.edd = edd;
    }

    public Integer getGestationalAge() {
        return gestationalAge;
    }

    public void setGestationalAge(Integer gestationalAge) {
        this.gestationalAge = gestationalAge;
    }

    public Integer getGravida() {
        return gravida;
    }

    public void setGravida(Integer gravida) {
        this.gravida = gravida;
    }

    public Integer getParity() {
        return parity;
    }

    public void setParity(Integer parity) {
        this.parity = parity;
    }

    public String getTimeHivDiagnosis() {
        return timeHivDiagnosis;
    }

    public void setTimeHivDiagnosis(String timeHivDiagnosis) {
        this.timeHivDiagnosis = timeHivDiagnosis;
    }

    public String getArvRegimenPast() {
        return arvRegimenPast;
    }

    public void setArvRegimenPast(String arvRegimenPast) {
        this.arvRegimenPast = arvRegimenPast;
    }

    public String getArvRegimenCurrent() {
        return arvRegimenCurrent;
    }

    public void setArvRegimenCurrent(String arvRegimenCurrent) {
        this.arvRegimenCurrent = arvRegimenCurrent;
    }

    public Date getDateArvRegimenCurrent() {
        return dateArvRegimenCurrent;
    }

    public void setDateArvRegimenCurrent(Date dateArvRegimenCurrent) {
        this.dateArvRegimenCurrent = dateArvRegimenCurrent;
    }

    public String getSyphilisTested() {
        return syphilisTested;
    }

    public void setSyphilisTested(String syphilisTested) {
        this.syphilisTested = syphilisTested;
    }

    public String getSyphilisTestResult() {
        return syphilisTestResult;
    }

    public void setSyphilisTestResult(String syphilisTestResult) {
        this.syphilisTestResult = syphilisTestResult;
    }

    public String getSyphilisTreated() {
        return syphilisTreated;
    }

    public void setSyphilisTreated(String syphilisTreated) {
        this.syphilisTreated = syphilisTreated;
    }

    public String getHepatitisBTestResult() {
        return hepatitisBTestResult;
    }

    public void setHepatitisBTestResult(String hepatitisBTestResult) {
        this.hepatitisBTestResult = hepatitisBTestResult;
    }

    public String getHepatitisBTested() {
        return hepatitisBTested;
    }

    public void setHepatitisBTested(String hepatitisBTested) {
        this.hepatitisBTested = hepatitisBTested;
    }

    public String getHepatitisCTestResult() {
        return hepatitisCTestResult;
    }

    public void setHepatitisCTestResult(String hepatitisCTestResult) {
        this.hepatitisCTestResult = hepatitisCTestResult;
    }

    public String getHepatitisCTested() {
        return hepatitisCTested;
    }

    public void setHepatitisCTested(String hepatitisCTested) {
        this.hepatitisCTested = hepatitisCTested;
    }

    public String getClinicStage() {
        return clinicStage;
    }

    public void setClinicStage(String clinicStage) {
        this.clinicStage = clinicStage;
    }

    public Date getDateConfirmedHiv() {
        return dateConfirmedHiv;
    }

    public void setDateConfirmedHiv(Date dateConfirmedHiv) {
        this.dateConfirmedHiv = dateConfirmedHiv;
    }

    public Date getDateNextAppointment() {
        return dateNextAppointment;
    }

    public void setDateNextAppointment(Date dateNextAppointment) {
        this.dateNextAppointment = dateNextAppointment;
    }

    public String getFuncStatus() {
        return funcStatus;
    }

    public void setFuncStatus(String funcStatus) {
        this.funcStatus = funcStatus;
    }

    public Double getBodyWeight() {
        return bodyWeight;
    }

    public void setBodyWeight(Double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    public Double getHeight() {
        return height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    public String getCd4Ordered() {
        return cd4Ordered;
    }

    public void setCd4Ordered(String cd4Ordered) {
        this.cd4Ordered = cd4Ordered;
    }

    public Double getCd4() {
        return cd4;
    }

    public void setCd4(Double cd4) {
        this.cd4 = cd4;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    public Integer getNumberAncVisit() {
        return numberAncVisit;
    }

    public void setNumberAncVisit(Integer numberAncVisit) {
        this.numberAncVisit = numberAncVisit;
    }

    public Date getDateCd4() {
        return dateCd4;
    }

    public void setDateCd4(Date dateCd4) {
        this.dateCd4 = dateCd4;
    }

    public String getViralLoadTestDone() {
        return viralLoadTestDone;
    }

    public void setViralLoadTestDone(String viralLoadTestDone) {
        this.viralLoadTestDone = viralLoadTestDone;
    }

    public Date getDateViralLoad() {
        return dateViralLoad;
    }

    public void setDateViralLoad(Date dateViralLoad) {
        this.dateViralLoad = dateViralLoad;
    }

    public String getViralLoadResult() {
        return viralLoadResult;
    }

    public void setViralLoadResult(String viralLoadResult) {
        this.viralLoadResult = viralLoadResult;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    
    
}


