package org.fhi360.lamis.model;
// Generated 25-Jul-2014 16:58:00 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Child generated by hbm2java
 */
public class Child implements java.io.Serializable {

    private long childId;
    private long patientId;
    private long facilityId;
    private long motherId;
    private long ancId;
    private long deliveryId;
    private String referenceNum;
    private String hospitalNumber;
    private String surname;
    private String otherNames;
    private Date dateBirth;
    private String gender;
    private String arv;
    private String hepb;
    private String hbv;
    private Double bodyWeight;
    private Integer apgarScore;
    private String status;
    private String arvTiming;
    private String registrationStatus;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
    private Set childfollowups = new HashSet(0);
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Child() {
    }

    public Child(long patientId, long facilityId, String hospitalNumber) {
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.hospitalNumber = hospitalNumber;
    }

    public Child(long childId, long patientId, long facilityId, long motherId, long ancId, long deliveryId, String referenceNum, String hospitalNumber, String surname, String otherNames, Date dateBirth, String gender, String arv, String hepb, String hbv, Double bodyWeight, Integer apgarScore, String status, String arvTiming, String registrationStatus, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.childId = childId;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.motherId = motherId;
        this.ancId = ancId;
        this.deliveryId = deliveryId;
        this.referenceNum = referenceNum;
        this.hospitalNumber = hospitalNumber;
        this.surname = surname;
        this.otherNames = otherNames;
        this.dateBirth = dateBirth;
        this.gender = gender;
        this.arv = arv;
        this.hepb = hepb;
        this.hbv = hbv;
        this.bodyWeight = bodyWeight;
        this.apgarScore = apgarScore;
        this.status = status;
        this.arvTiming = arvTiming;
        this.registrationStatus = registrationStatus;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

    public long getChildId() {
        return childId;
    }

    public void setChildId(long childId) {
        this.childId = childId;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public long getMotherId() {
        return motherId;
    }

    public void setMotherId(long motherId) {
        this.motherId = motherId;
    }

    public long getAncId() {
        return ancId;
    }

    public void setAncId(long ancId) {
        this.ancId = ancId;
    }

    public long getDeliveryId() {
        return deliveryId;
    }

    public void setDeliveryId(long deliveryId) {
        this.deliveryId = deliveryId;
    }

    public String getReferenceNum() {
        return referenceNum;
    }

    public void setReferenceNum(String referenceNum) {
        this.referenceNum = referenceNum;
    }

    public String getHospitalNumber() {
        return hospitalNumber;
    }

    public void setHospitalNumber(String hospitalNumber) {
        this.hospitalNumber = hospitalNumber;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getOtherNames() {
        return otherNames;
    }

    public void setOtherNames(String otherNames) {
        this.otherNames = otherNames;
    }

    public Date getDateBirth() {
        return dateBirth;
    }

    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getArv() {
        return arv;
    }

    public void setArv(String arv) {
        this.arv = arv;
    }

    public String getHepb() {
        return hepb;
    }

    public void setHepb(String hepb) {
        this.hepb = hepb;
    }

    public String getHbv() {
        return hbv;
    }

    public void setHbv(String hbv) {
        this.hbv = hbv;
    }

    public Double getBodyWeight() {
        return bodyWeight;
    }

    public void setBodyWeight(Double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    public Integer getApgarScore() {
        return apgarScore;
    }

    public void setApgarScore(Integer apgarScore) {
        this.apgarScore = apgarScore;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getArvTiming() {
        return arvTiming;
    }

    public void setArvTiming(String arvTiming) {
        this.arvTiming = arvTiming;
    }

    public String getRegistrationStatus() {
        return registrationStatus;
    }

    public void setRegistrationStatus(String registrationStatus) {
        this.registrationStatus = registrationStatus;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    public Set getChildfollowups() {
        return childfollowups;
    }

    public void setChildfollowups(Set childfollowups) {
        this.childfollowups = childfollowups;
    }

    @Override
    public String toString() {
        return "Child{" + "childId=" + childId + ", patientId=" + patientId + ", facilityId=" + facilityId + ", motherId=" + motherId + ", ancId=" + ancId + ", deliveryId=" + deliveryId + ", referenceNum=" + referenceNum + ", hospitalNumber=" + hospitalNumber + ", surname=" + surname + ", otherNames=" + otherNames + ", dateBirth=" + dateBirth + ", gender=" + gender + ", arv=" + arv + ", hepb=" + hepb + ", hbv=" + hbv + ", bodyWeight=" + bodyWeight + ", apgarScore=" + apgarScore + ", status=" + status + ", arvTiming=" + arvTiming + ", registrationStatus=" + registrationStatus + ", timeStamp=" + timeStamp + '}';
    }

}
