package org.fhi360.lamis.model;
// Generated 19-Jul-2014 19:48:23 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Childfollowup generated by hbm2java
 */
public class Childfollowup implements java.io.Serializable {

    private long childfollowupId;
    private Child child;
    private String referenceNum;
    private long facilityId;
    private Date dateVisit;
    private Integer ageVisit;
    private Date dateNvpInitiated;
    private Integer ageNvpInitiated;
    private Date dateCotrimInitiated;
    private Integer ageCotrimInitiated;
    private Double bodyWeight;
    private Double height;
    private String feeding;
    private String arvType;
    private String arvTiming;
    private String infantOutcome;
    private Date dateLinkedToArt;
    private String arv;
    private String cotrim;
    private Date dateSampleCollected;
    private String reasonPcr;
    private Date dateSampleSent;
    private Date datePcrResult;
    private String pcrResult;
    private String rapidTest;
    private Date dateRapidTest;
    private String rapidTestResult;
    private String caregiverGivenResult;

    private String childOutcome;
    private String referred;
    private Date dateNextVisit;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Childfollowup() {
    }

    public Childfollowup(Child child, long facilityId) {
        this.child = child;
        this.facilityId = facilityId;
    }

    public Childfollowup(long childfollowupId, Child child, String referenceNum, long facilityId, Date dateVisit, Integer ageVisit, Date dateNvpInitiated, Integer ageNvpInitiated, Date dateCotrimInitiated, Integer ageCotrimInitiated, Double bodyWeight, Double height, String feeding, String arvType, String arvTiming, String infantOutcome, Date dateLinkedToArt, String arv, String cotrim, Date dateSampleCollected, String reasonPcr, Date dateSampleSent, Date datePcrResult, String pcrResult, String rapidTest, Date dateRapidTest, String rapidTestResult, String caregiverGivenResult, String childOutcome, String referred, Date dateNextVisit, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.childfollowupId = childfollowupId;
        this.child = child;
        this.referenceNum = referenceNum;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.ageVisit = ageVisit;
        this.dateNvpInitiated = dateNvpInitiated;
        this.ageNvpInitiated = ageNvpInitiated;
        this.dateCotrimInitiated = dateCotrimInitiated;
        this.ageCotrimInitiated = ageCotrimInitiated;
        this.bodyWeight = bodyWeight;
        this.height = height;
        this.feeding = feeding;
        this.arvType = arvType;
        this.arvTiming = arvTiming;
        this.infantOutcome = infantOutcome;
        this.dateLinkedToArt = dateLinkedToArt;
        this.arv = arv;
        this.cotrim = cotrim;
        this.dateSampleCollected = dateSampleCollected;
        this.reasonPcr = reasonPcr;
        this.dateSampleSent = dateSampleSent;
        this.datePcrResult = datePcrResult;
        this.pcrResult = pcrResult;
        this.rapidTest = rapidTest;
        this.dateRapidTest = dateRapidTest;
        this.rapidTestResult = rapidTestResult;
        this.caregiverGivenResult = caregiverGivenResult;
        this.childOutcome = childOutcome;
        this.referred = referred;
        this.dateNextVisit = dateNextVisit;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }


    public long getChildfollowupId() {
        return childfollowupId;
    }

    public void setChildfollowupId(long childfollowupId) {
        this.childfollowupId = childfollowupId;
    }

    public String getReferenceNum() {
        return referenceNum;
    }

    public void setReferenceNum(String referenceNum) {
        this.referenceNum = referenceNum;
    }

    public Child getChild() {
        return child;
    }

    public void setChild(Child child) {
        this.child = child;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public Integer getAgeVisit() {
        return ageVisit;
    }

    public void setAgeVisit(Integer ageVisit) {
        this.ageVisit = ageVisit;
    }

    public Date getDateNvpInitiated() {
        return dateNvpInitiated;
    }

    public void setDateNvpInitiated(Date dateNvpInitiated) {
        this.dateNvpInitiated = dateNvpInitiated;
    }

    public Integer getAgeNvpInitiated() {
        return ageNvpInitiated;
    }

    public void setAgeNvpInitiated(Integer ageNvpInitiated) {
        this.ageNvpInitiated = ageNvpInitiated;
    }

    public Date getDateCotrimInitiated() {
        return dateCotrimInitiated;
    }

    public void setDateCotrimInitiated(Date dateCotrimInitiated) {
        this.dateCotrimInitiated = dateCotrimInitiated;
    }

    public Integer getAgeCotrimInitiated() {
        return ageCotrimInitiated;
    }

    public void setAgeCotrimInitiated(Integer ageCotrimInitiated) {
        this.ageCotrimInitiated = ageCotrimInitiated;
    }

    public Double getBodyWeight() {
        return bodyWeight;
    }

    public void setBodyWeight(Double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    public Double getHeight() {
        return height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    public String getFeeding() {
        return feeding;
    }

    public void setFeeding(String feeding) {
        this.feeding = feeding;
    }

    public String getArvType() {
        return arvType;
    }

    public void setArvType(String arvType) {
        this.arvType = arvType;
    }

    public String getArvTiming() {
        return arvTiming;
    }

    public void setArvTiming(String arvTiming) {
        this.arvTiming = arvTiming;
    }

    public String getInfantOutcome() {
        return infantOutcome;
    }

    public void setInfantOutcome(String infantOutcome) {
        this.infantOutcome = infantOutcome;
    }

    public Date getDateLinkedToArt() {
        return dateLinkedToArt;
    }

    public void setDateLinkedToArt(Date dateLinkedToArt) {
        this.dateLinkedToArt = dateLinkedToArt;
    }

    public String getArv() {
        return arv;
    }

    public void setArv(String arv) {
        this.arv = arv;
    }

    public String getCotrim() {
        return cotrim;
    }

    public void setCotrim(String cotrim) {
        this.cotrim = cotrim;
    }

    public Date getDateSampleCollected() {
        return dateSampleCollected;
    }

    public void setDateSampleCollected(Date dateSampleCollected) {
        this.dateSampleCollected = dateSampleCollected;
    }

    public String getReasonPcr() {
        return reasonPcr;
    }

    public void setReasonPcr(String reasonPcr) {
        this.reasonPcr = reasonPcr;
    }

    public Date getDateSampleSent() {
        return dateSampleSent;
    }

    public void setDateSampleSent(Date dateSampleSent) {
        this.dateSampleSent = dateSampleSent;
    }

    public Date getDatePcrResult() {
        return datePcrResult;
    }

    public void setDatePcrResult(Date datePcrResult) {
        this.datePcrResult = datePcrResult;
    }

    public String getPcrResult() {
        return pcrResult;
    }

    public void setPcrResult(String pcrResult) {
        this.pcrResult = pcrResult;
    }

    public String getRapidTest() {
        return rapidTest;
    }

    public void setRapidTest(String rapidTest) {
        this.rapidTest = rapidTest;
    }

    public Date getDateRapidTest() {
        return dateRapidTest;
    }

    public void setDateRapidTest(Date dateRapidTest) {
        this.dateRapidTest = dateRapidTest;
    }

    public String getRapidTestResult() {
        return rapidTestResult;
    }

    public void setRapidTestResult(String rapidTestResult) {
        this.rapidTestResult = rapidTestResult;
    }

    public String getCaregiverGivenResult() {
        return caregiverGivenResult;
    }

    public void setCaregiverGivenResult(String caregiverGivenResult) {
        this.caregiverGivenResult = caregiverGivenResult;
    }

    public String getChildOutcome() {
        return childOutcome;
    }

    public void setChildOutcome(String childOutcome) {
        this.childOutcome = childOutcome;
    }

    public String getReferred() {
        return referred;
    }

    public void setReferred(String referred) {
        this.referred = referred;
    }

    public Date getDateNextVisit() {
        return dateNextVisit;
    }

    public void setDateNextVisit(Date dateNextVisit) {
        this.dateNextVisit = dateNextVisit;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
