package org.fhi360.lamis.model;
// Generated 26-Sep-2014 01:29:14 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Chroniccarehistory generated by hbm2java
 */
public class Chroniccare implements java.io.Serializable {

    private long chroniccareId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private Date dateVisit;
    private String clientType;
    private String currentStatus;
    private String pregnancyStatus;
    private String clinicStage;
    private Double lastCd4;
    private Date dateLastCd4;
    private Double lastViralLoad;
    private Date dateLastViralLoad;
    private String eligibleCd4;
    private String eligibleViralLoad;
    private Integer cotrimEligibility1;
    private Integer cotrimEligibility2;
    private Integer cotrimEligibility3;
    private Integer cotrimEligibility4;
    private Integer cotrimEligibility5;
    private String ipt;
    private String inh;
    private String tbTreatment;
    private Date dateStartedTbTreatment;
    private String tbReferred;
    private String eligibleIpt;
    private String tbValues;
    private Double bodyWeight;
    private Double height;
    private String bmi;
    private Double muac;
    private String muacPediatrics;
    private String muacPregnant;
    private String supplementaryFood;
    private String nutritionalStatusReferred;
    private String gbv1;
    private String gbv1Referred;
    private String gbv2;
    private String gbv2Referred;
    private String hypertensive;
    private String firstHypertensive;
    private String bpAbove;
    private String bpReferred;
    private String diabetic;
    private String firstDiabetic;
    private String dmReferred;
    private String dmValues;
    private String phdp1;
    private String phdp1ServicesProvided;
    private String phdp2;
    private String phdp2ServicesProvided;
    private String phdp3;
    private String phdp3ServicesProvided;
    private String phdp4;
    private String phdp4ServicesProvided;
    private String phdp5;
    private String phdp5ServicesProvided;
    private Integer phdp6;
    private String phdp6ServicesProvided;
    private Integer phdp7;
    private String phdp7ServicesProvided;
    private String phdp8;
    private String phdp8ServicesProvided;
    private String phdp9ServicesProvided;
    private String reproductiveIntentions1;
    private String reproductiveIntentions1Referred;
    private String reproductiveIntentions2;
    private String reproductiveIntentions2Referred;
    private String reproductiveIntentions3;
    private String reproductiveIntentions3Referred;
    private String malariaPrevention1;
    private String malariaPrevention1Referred;
    private String malariaPrevention2;
    private String malariaPrevention2Referred;
    private long communitypharmId;
    private Long userId;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Chroniccare() {
    }

    public Chroniccare(long chroniccareId, Patient patient, long facilityId, Date dateVisit) {
        this.chroniccareId = chroniccareId;
        this.patient = patient;
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }


    public long getChroniccareId() {
        return this.chroniccareId;
    }

    public void setChroniccareId(long chroniccareId) {
        this.chroniccareId = chroniccareId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return this.dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public String getCurrentStatus() {
        return this.currentStatus;
    }

    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public String getClinicStage() {
        return this.clinicStage;
    }

    public void setClinicStage(String clinicStage) {
        this.clinicStage = clinicStage;
    }

    public Double getLastCd4() {
        return this.lastCd4;
    }

    public void setLastCd4(Double lastCd4) {
        this.lastCd4 = lastCd4;
    }

    public Date getDateLastCd4() {
        return this.dateLastCd4;
    }

    public void setDateLastCd4(Date dateLastCd4) {
        this.dateLastCd4 = dateLastCd4;
    }

    public Double getLastViralLoad() {
        return this.lastViralLoad;
    }

    public void setLastViralLoad(Double lastViralLoad) {
        this.lastViralLoad = lastViralLoad;
    }

    public Date getDateLastViralLoad() {
        return this.dateLastViralLoad;
    }

    public void setDateLastViralLoad(Date dateLastViralLoad) {
        this.dateLastViralLoad = dateLastViralLoad;
    }

    public String getEligibleCd4() {
        return this.eligibleCd4;
    }

    public void setEligibleCd4(String eligibleCd4) {
        this.eligibleCd4 = eligibleCd4;
    }

    public String getEligibleViralLoad() {
        return this.eligibleViralLoad;
    }

    public void setEligibleViralLoad(String eligibleViralLoad) {
        this.eligibleViralLoad = eligibleViralLoad;
    }

    public Integer getCotrimEligibility1() {
        return this.cotrimEligibility1;
    }

    public void setCotrimEligibility1(Integer cotrimEligibility1) {
        this.cotrimEligibility1 = cotrimEligibility1;
    }

    public Integer getCotrimEligibility2() {
        return this.cotrimEligibility2;
    }

    public void setCotrimEligibility2(Integer cotrimEligibility2) {
        this.cotrimEligibility2 = cotrimEligibility2;
    }

    public Integer getCotrimEligibility3() {
        return this.cotrimEligibility3;
    }

    public void setCotrimEligibility3(Integer cotrimEligibility3) {
        this.cotrimEligibility3 = cotrimEligibility3;
    }

    public Integer getCotrimEligibility4() {
        return this.cotrimEligibility4;
    }

    public void setCotrimEligibility4(Integer cotrimEligibility4) {
        this.cotrimEligibility4 = cotrimEligibility4;
    }

    public Integer getCotrimEligibility5() {
        return this.cotrimEligibility5;
    }

    public void setCotrimEligibility5(Integer cotrimEligibility5) {
        this.cotrimEligibility5 = cotrimEligibility5;
    }

    public String getIpt() {
        return this.ipt;
    }

    public void setIpt(String ipt) {
        this.ipt = ipt;
    }

    public String getTbTreatment() {
        return this.tbTreatment;
    }

    public void setTbTreatment(String tbTreatment) {
        this.tbTreatment = tbTreatment;
    }

    public Date getDateStartedTbTreatment() {
        return this.dateStartedTbTreatment;
    }

    public void setDateStartedTbTreatment(Date dateStartedTbTreatment) {
        this.dateStartedTbTreatment = dateStartedTbTreatment;
    }

    public String getTbReferred() {
        return this.tbReferred;
    }

    public void setTbReferred(String tbReferred) {
        this.tbReferred = tbReferred;
    }

    public String getEligibleIpt() {
        return this.eligibleIpt;
    }

    public void setEligibleIpt(String eligibleIpt) {
        this.eligibleIpt = eligibleIpt;
    }

    public String getTbValues() {
        return this.tbValues;
    }

    public void setTbValues(String tbValues) {
        this.tbValues = tbValues;
    }

    public String getBmi() {
        return this.bmi;
    }

    public void setBmi(String bmi) {
        this.bmi = bmi;
    }

    public String getMuacPediatrics() {
        return this.muacPediatrics;
    }

    public void setMuacPediatrics(String muacPediatrics) {
        this.muacPediatrics = muacPediatrics;
    }

    public String getSupplementaryFood() {
        return this.supplementaryFood;
    }

    public void setSupplementaryFood(String supplementaryFood) {
        this.supplementaryFood = supplementaryFood;
    }

    public String getNutritionalStatusReferred() {
        return this.nutritionalStatusReferred;
    }

    public void setNutritionalStatusReferred(String nutritionalStatusReferred) {
        this.nutritionalStatusReferred = nutritionalStatusReferred;
    }

    public String getGbv1() {
        return this.gbv1;
    }

    public void setGbv1(String gbv1) {
        this.gbv1 = gbv1;
    }

    public String getGbv1Referred() {
        return this.gbv1Referred;
    }

    public void setGbv1Referred(String gbv1Referred) {
        this.gbv1Referred = gbv1Referred;
    }

    public String getGbv2() {
        return this.gbv2;
    }

    public void setGbv2(String gbv2) {
        this.gbv2 = gbv2;
    }

    public String getGbv2Referred() {
        return this.gbv2Referred;
    }

    public void setGbv2Referred(String gbv2Referred) {
        this.gbv2Referred = gbv2Referred;
    }

    public String getHypertensive() {
        return this.hypertensive;
    }

    public void setHypertensive(String hypertensive) {
        this.hypertensive = hypertensive;
    }

    public String getFirstHypertensive() {
        return this.firstHypertensive;
    }

    public void setFirstHypertensive(String firstHypertensive) {
        this.firstHypertensive = firstHypertensive;
    }

    public String getBpAbove() {
        return this.bpAbove;
    }

    public void setBpAbove(String bpAbove) {
        this.bpAbove = bpAbove;
    }

    public String getBpReferred() {
        return this.bpReferred;
    }

    public void setBpReferred(String bpReferred) {
        this.bpReferred = bpReferred;
    }

    public String getDiabetic() {
        return this.diabetic;
    }

    public void setDiabetic(String diabetic) {
        this.diabetic = diabetic;
    }

    public String getFirstDiabetic() {
        return this.firstDiabetic;
    }

    public void setFirstDiabetic(String firstDiabetic) {
        this.firstDiabetic = firstDiabetic;
    }

    public String getDmReferred() {
        return this.dmReferred;
    }

    public void setDmReferred(String dmReferred) {
        this.dmReferred = dmReferred;
    }

    public String getDmValues() {
        return this.dmValues;
    }

    public void setDmValues(String dmValues) {
        this.dmValues = dmValues;
    }

    public String getPhdp1() {
        return this.phdp1;
    }

    public void setPhdp1(String phdp1) {
        this.phdp1 = phdp1;
    }

    public String getPhdp1ServicesProvided() {
        return this.phdp1ServicesProvided;
    }

    public void setPhdp1ServicesProvided(String phdp1ServicesProvided) {
        this.phdp1ServicesProvided = phdp1ServicesProvided;
    }

    public String getPhdp2() {
        return this.phdp2;
    }

    public void setPhdp2(String phdp2) {
        this.phdp2 = phdp2;
    }

    public String getPhdp2ServicesProvided() {
        return this.phdp2ServicesProvided;
    }

    public void setPhdp2ServicesProvided(String phdp2ServicesProvided) {
        this.phdp2ServicesProvided = phdp2ServicesProvided;
    }

    public String getPhdp3() {
        return this.phdp3;
    }

    public void setPhdp3(String phdp3) {
        this.phdp3 = phdp3;
    }

    public String getPhdp3ServicesProvided() {
        return this.phdp3ServicesProvided;
    }

    public void setPhdp3ServicesProvided(String phdp3ServicesProvided) {
        this.phdp3ServicesProvided = phdp3ServicesProvided;
    }

    public String getPhdp4() {
        return this.phdp4;
    }

    public void setPhdp4(String phdp4) {
        this.phdp4 = phdp4;
    }

    public String getPhdp4ServicesProvided() {
        return this.phdp4ServicesProvided;
    }

    public void setPhdp4ServicesProvided(String phdp4ServicesProvided) {
        this.phdp4ServicesProvided = phdp4ServicesProvided;
    }

    public String getPhdp5() {
        return this.phdp5;
    }

    public void setPhdp5(String phdp5) {
        this.phdp5 = phdp5;
    }

    public String getPhdp5ServicesProvided() {
        return this.phdp5ServicesProvided;
    }

    public void setPhdp5ServicesProvided(String phdp5ServicesProvided) {
        this.phdp5ServicesProvided = phdp5ServicesProvided;
    }

    public Integer getPhdp6() {
        return this.phdp6;
    }

    public void setPhdp6(Integer phdp6) {
        this.phdp6 = phdp6;
    }

    public String getPhdp6ServicesProvided() {
        return this.phdp6ServicesProvided;
    }

    public void setPhdp6ServicesProvided(String phdp6ServicesProvided) {
        this.phdp6ServicesProvided = phdp6ServicesProvided;
    }

    public Integer getPhdp7() {
        return this.phdp7;
    }

    public void setPhdp7(Integer phdp7) {
        this.phdp7 = phdp7;
    }

    public String getPhdp7ServicesProvided() {
        return this.phdp7ServicesProvided;
    }

    public void setPhdp7ServicesProvided(String phdp7ServicesProvided) {
        this.phdp7ServicesProvided = phdp7ServicesProvided;
    }

    public String getPhdp8() {
        return this.phdp8;
    }

    public void setPhdp8(String phdp8) {
        this.phdp8 = phdp8;
    }

    public String getPhdp8ServicesProvided() {
        return this.phdp8ServicesProvided;
    }

    public void setPhdp8ServicesProvided(String phdp8ServicesProvided) {
        this.phdp8ServicesProvided = phdp8ServicesProvided;
    }

    public String getPhdp9ServicesProvided() {
        return this.phdp9ServicesProvided;
    }

    public void setPhdp9ServicesProvided(String phdp9ServicesProvided) {
        this.phdp9ServicesProvided = phdp9ServicesProvided;
    }

    public String getReproductiveIntentions1() {
        return this.reproductiveIntentions1;
    }

    public void setReproductiveIntentions1(String reproductiveIntentions1) {
        this.reproductiveIntentions1 = reproductiveIntentions1;
    }

    public String getReproductiveIntentions1Referred() {
        return this.reproductiveIntentions1Referred;
    }

    public void setReproductiveIntentions1Referred(String reproductiveIntentions1Referred) {
        this.reproductiveIntentions1Referred = reproductiveIntentions1Referred;
    }

    public String getReproductiveIntentions2() {
        return this.reproductiveIntentions2;
    }

    public void setReproductiveIntentions2(String reproductiveIntentions2) {
        this.reproductiveIntentions2 = reproductiveIntentions2;
    }

    public String getReproductiveIntentions2Referred() {
        return this.reproductiveIntentions2Referred;
    }

    public void setReproductiveIntentions2Referred(String reproductiveIntentions2Referred) {
        this.reproductiveIntentions2Referred = reproductiveIntentions2Referred;
    }

    public String getReproductiveIntentions3() {
        return this.reproductiveIntentions3;
    }

    public void setReproductiveIntentions3(String reproductiveIntentions3) {
        this.reproductiveIntentions3 = reproductiveIntentions3;
    }

    public String getReproductiveIntentions3Referred() {
        return this.reproductiveIntentions3Referred;
    }

    public void setReproductiveIntentions3Referred(String reproductiveIntentions3Referred) {
        this.reproductiveIntentions3Referred = reproductiveIntentions3Referred;
    }

    public String getMalariaPrevention1() {
        return this.malariaPrevention1;
    }

    public void setMalariaPrevention1(String malariaPrevention1) {
        this.malariaPrevention1 = malariaPrevention1;
    }

    public String getMalariaPrevention1Referred() {
        return this.malariaPrevention1Referred;
    }

    public void setMalariaPrevention1Referred(String malariaPrevention1Referred) {
        this.malariaPrevention1Referred = malariaPrevention1Referred;
    }

    public String getMalariaPrevention2() {
        return this.malariaPrevention2;
    }

    public void setMalariaPrevention2(String malariaPrevention2) {
        this.malariaPrevention2 = malariaPrevention2;
    }

    public String getMalariaPrevention2Referred() {
        return this.malariaPrevention2Referred;
    }

    public void setMalariaPrevention2Referred(String malariaPrevention2Referred) {
        this.malariaPrevention2Referred = malariaPrevention2Referred;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the clientType
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * @param clientType the clientType to set
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * @return the pregnancyStatus
     */
    public String getPregnancyStatus() {
        return pregnancyStatus;
    }

    /**
     * @param pregnancyStatus the pregnancyStatus to set
     */
    public void setPregnancyStatus(String pregnancyStatus) {
        this.pregnancyStatus = pregnancyStatus;
    }

    /**
     * @return the muacPregnant
     */
    public String getMuacPregnant() {
        return muacPregnant;
    }

    /**
     * @param muacPregnant the muacPregnant to set
     */
    public void setMuacPregnant(String muacPregnant) {
        this.muacPregnant = muacPregnant;
    }

    /**
     * @return the bodyWeight
     */
    public Double getBodyWeight() {
        return bodyWeight;
    }

    /**
     * @param bodyWeight the bodyWeight to set
     */
    public void setBodyWeight(Double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    /**
     * @return the height
     */
    public Double getHeight() {
        return height;
    }

    /**
     * @param height the height to set
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * @return the muac
     */
    public Double getMuac() {
        return muac;
    }

    /**
     * @param muac the muac to set
     */
    public void setMuac(Double muac) {
        this.muac = muac;
    }

    /**
     * @return the inh
     */
    public String getInh() {
        return inh;
    }

    /**
     * @param inh the inh to set
     */
    public void setInh(String inh) {
        this.inh = inh;
    }

    /**
     * @return the communitypharmId
     */
    public long getCommunitypharmId() {
        return communitypharmId;
    }

    /**
     * @param communitypharmId the communitypharmId to set
     */
    public void setCommunitypharmId(long communitypharmId) {
        this.communitypharmId = communitypharmId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
