package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Adhere generated by hbm2java
 */
public class Dmscreen  implements java.io.Serializable {


     private long dmscreenId;
     private String description;

    public Dmscreen() {
    }

    public Dmscreen(long dmscreenId, String description) {
       this.dmscreenId = dmscreenId;
       this.description = description;
    }
   
    public long getDmscreenId() {
        return this.dmscreenId;
    }
    
    public void setDmscreenId(long dmscreenId) {
        this.dmscreenId = dmscreenId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


