package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Drug generated by hbm2java
 */
public class Drug  implements java.io.Serializable {


     private long drugId;
     private String abbrev;
     private String name;
     private String strength;
     private int packSize;
     private String doseform;
     private Integer morning;
     private Integer afternoon;
     private Integer evening;
     private long itemId;
     private Set<Regimendrug> regimendrugs = new HashSet<Regimendrug>(0);

    public Drug() {
    }

	
    public Drug(long drugId, String abbrev, String name, String strength, int packSize, long itemId) {
        this.drugId = drugId;
        this.abbrev = abbrev;
        this.name = name;
        this.strength = strength;
        this.packSize = packSize;
        this.itemId = itemId;
    }
    public Drug(long drugId, String abbrev, String name, String strength, int packSize, String doseform, Integer morning, Integer afternoon, Integer evening, long itemId, Set<Regimendrug> regimendrugs) {
       this.drugId = drugId;
       this.abbrev = abbrev;
       this.name = name;
       this.strength = strength;
       this.packSize = packSize;
       this.doseform = doseform;
       this.morning = morning;
       this.afternoon = afternoon;
       this.evening = evening;
       this.itemId = itemId;
       this.regimendrugs = regimendrugs;
    }
   
    public long getDrugId() {
        return this.drugId;
    }
    
    public void setDrugId(long drugId) {
        this.drugId = drugId;
    }
    public String getAbbrev() {
        return this.abbrev;
    }
    
    public void setAbbrev(String abbrev) {
        this.abbrev = abbrev;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStrength() {
        return this.strength;
    }
    
    public void setStrength(String strength) {
        this.strength = strength;
    }
    public int getPackSize() {
        return this.packSize;
    }
    
    public void setPackSize(int packSize) {
        this.packSize = packSize;
    }
    public String getDoseform() {
        return this.doseform;
    }
    
    public void setDoseform(String doseform) {
        this.doseform = doseform;
    }
    public Integer getMorning() {
        return this.morning;
    }
    
    public void setMorning(Integer morning) {
        this.morning = morning;
    }
    public Integer getAfternoon() {
        return this.afternoon;
    }
    
    public void setAfternoon(Integer afternoon) {
        this.afternoon = afternoon;
    }
    public Integer getEvening() {
        return this.evening;
    }
    
    public void setEvening(Integer evening) {
        this.evening = evening;
    }
    public long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(long itemId) {
        this.itemId = itemId;
    }
    public Set<Regimendrug> getRegimendrugs() {
        return this.regimendrugs;
    }
    
    public void setRegimendrugs(Set<Regimendrug> regimendrugs) {
        this.regimendrugs = regimendrugs;
    }




}


