package org.fhi360.lamis.model;
// Generated Oct 16, 2014 12:09:06 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Eid generated by hbm2java
 */
public class Eid implements java.io.Serializable {

    private long eidId;
    private long facilityId;
    private String labno;
    private String motherName;
    private String motherAddress;
    private String motherPhone;
    private String senderName;
    private String senderDesignation;
    private String senderAddress;
    private String senderPhone;
    private String reasonPcr;
    private String rapidTestDone;
    private Date dateRapidTest;
    private String rapidTestResult;
    private String motherArtReceived;
    private String motherProphylaxReceived;
    private String childProphylaxReceived;
    private String breastfedEver;
    private String feedingMethod;
    private String breastfedNow;
    private Integer feedingCessationAge;
    private String cotrim;
    private Date nextAppointment;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
     private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    

    public Eid() {
    }

    public Eid(long eidId, long specimenId, long facilityId, String labno) {
        this.eidId = eidId;
        this.facilityId = facilityId;
        this.labno = labno;
    }

    public Eid(long eidId, long facilityId, String labno, String motherName, String motherAddress, String motherPhone, String senderName, String senderDesignation, String senderAddress, String senderPhone, String reasonPcr, String rapidTestDone, Date dateRapidTest, String rapidTestResult, String motherArtReceived, String motherProphylaxReceived, String childProphylaxReceived, String breastfedEver, String feedingMethod, String breastfedNow, Integer feedingCessationAge, String cotrim, Date nextAppointment, Date timeStamp, Integer uploaded, Date timeUploaded, String uuid) {
        this.eidId = eidId;
        this.facilityId = facilityId;
        this.labno = labno;
        this.motherName = motherName;
        this.motherAddress = motherAddress;
        this.motherPhone = motherPhone;
        this.senderName = senderName;
        this.senderDesignation = senderDesignation;
        this.senderAddress = senderAddress;
        this.senderPhone = senderPhone;
        this.reasonPcr = reasonPcr;
        this.rapidTestDone = rapidTestDone;
        this.dateRapidTest = dateRapidTest;
        this.rapidTestResult = rapidTestResult;
        this.motherArtReceived = motherArtReceived;
        this.motherProphylaxReceived = motherProphylaxReceived;
        this.childProphylaxReceived = childProphylaxReceived;
        this.breastfedEver = breastfedEver;
        this.feedingMethod = feedingMethod;
        this.breastfedNow = breastfedNow;
        this.feedingCessationAge = feedingCessationAge;
        this.cotrim = cotrim;
        this.nextAppointment = nextAppointment;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

   

    public long getEidId() {
        return this.eidId;
    }

    public void setEidId(long eidId) {
        this.eidId = eidId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public String getLabno() {
        return this.labno;
    }

    public void setLabno(String labno) {
        this.labno = labno;
    }

    public String getMotherName() {
        return this.motherName;
    }

    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    public String getMotherAddress() {
        return this.motherAddress;
    }

    public void setMotherAddress(String motherAddress) {
        this.motherAddress = motherAddress;
    }

    public String getMotherPhone() {
        return this.motherPhone;
    }

    public void setMotherPhone(String motherPhone) {
        this.motherPhone = motherPhone;
    }

    public String getSenderName() {
        return this.senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public String getSenderDesignation() {
        return this.senderDesignation;
    }

    public void setSenderDesignation(String senderDesignation) {
        this.senderDesignation = senderDesignation;
    }

    public String getSenderAddress() {
        return this.senderAddress;
    }

    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    public String getSenderPhone() {
        return this.senderPhone;
    }

    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone;
    }

    public String getReasonPcr() {
        return this.reasonPcr;
    }

    public void setReasonPcr(String reasonPcr) {
        this.reasonPcr = reasonPcr;
    }

    public String getRapidTestDone() {
        return this.rapidTestDone;
    }

    public void setRapidTestDone(String rapidTestDone) {
        this.rapidTestDone = rapidTestDone;
    }

    public Date getDateRapidTest() {
        return this.dateRapidTest;
    }

    public void setDateRapidTest(Date dateRapidTest) {
        this.dateRapidTest = dateRapidTest;
    }

    public String getRapidTestResult() {
        return this.rapidTestResult;
    }

    public void setRapidTestResult(String rapidTestResult) {
        this.rapidTestResult = rapidTestResult;
    }

    public String getMotherArtReceived() {
        return this.motherArtReceived;
    }

    public void setMotherArtReceived(String motherArtReceived) {
        this.motherArtReceived = motherArtReceived;
    }

    public String getMotherProphylaxReceived() {
        return this.motherProphylaxReceived;
    }

    public void setMotherProphylaxReceived(String motherProphylaxReceived) {
        this.motherProphylaxReceived = motherProphylaxReceived;
    }

    public String getChildProphylaxReceived() {
        return this.childProphylaxReceived;
    }

    public void setChildProphylaxReceived(String childProphylaxReceived) {
        this.childProphylaxReceived = childProphylaxReceived;
    }

    public String getBreastfedEver() {
        return this.breastfedEver;
    }

    public void setBreastfedEver(String breastfedEver) {
        this.breastfedEver = breastfedEver;
    }

    public String getFeedingMethod() {
        return this.feedingMethod;
    }

    public void setFeedingMethod(String feedingMethod) {
        this.feedingMethod = feedingMethod;
    }

    public String getBreastfedNow() {
        return this.breastfedNow;
    }

    public void setBreastfedNow(String breastfedNow) {
        this.breastfedNow = breastfedNow;
    }

    public Integer getFeedingCessationAge() {
        return this.feedingCessationAge;
    }

    public void setFeedingCessationAge(Integer feedingCessationAge) {
        this.feedingCessationAge = feedingCessationAge;
    }

    public String getCotrim() {
        return this.cotrim;
    }

    public void setCotrim(String cotrim) {
        this.cotrim = cotrim;
    }

    public Date getNextAppointment() {
        return this.nextAppointment;
    }

    public void setNextAppointment(Date nextAppointment) {
        this.nextAppointment = nextAppointment;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
