package org.fhi360.lamis.model;
// Generated Oct 15, 2014 11:39:23 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Exchange generated by hbm2java
 */
public class Exchange implements java.io.Serializable {

    /**
     * @return the eac
     */
    public Date getEac() {
        return eac;
    }

    private Long exchangeId;
    private long facilityId;
    private Date patient;
    private Date clinic;
    private Date pharmacy;
    private Date laboratory;
    private Date adrhistory;
    private Date oihistory;
    private Date adherehistory;
    private Date statushistory;
    private Date regimenhistory;
    private Date chroniccare;
    private Date tbscreenhistory;
    private Date dmscreenhistory;
    private Date anc;
    private Date delivery;
    private Date maternalfollowup;
    private Date child;
    private Date childfollowup;
    private Date partnerinformation;
    private Date nigqual;
    private Date specimen;
    private Date eid;
    private Date labno;
    private Date eac;
    private Date monitor;
    private Date export;
    private Date assessment;
    private Date hts;
    private Date indexcontact;
    private Date encounter;
    private Date drugtherapy;
    private Date mhtc;
    private Date appointment;

    public Exchange() {
    }

    public Exchange(long facilityId) {
        this.facilityId = facilityId;
    }

    public Exchange(Long exchangeId, long facilityId, Date patient, Date clinic, Date pharmacy, Date laboratory, Date adrhistory, Date oihistory, Date adherehistory, Date statushistory, Date regimenhistory, Date chroniccare, Date tbscreenhistory, Date dmscreenhistory, Date anc, Date delivery, Date maternalfollowup, Date child, Date childfollowup, Date partnerinformation, Date nigqual, Date specimen, Date eid, Date labno, Date eac, Date monitor, Date export, Date assessment, Date hts, Date indexcontact, Date encounter, Date drugtherapy, Date mhtc, Date appointment) {
        this.exchangeId = exchangeId;
        this.facilityId = facilityId;
        this.patient = patient;
        this.clinic = clinic;
        this.pharmacy = pharmacy;
        this.laboratory = laboratory;
        this.adrhistory = adrhistory;
        this.oihistory = oihistory;
        this.adherehistory = adherehistory;
        this.statushistory = statushistory;
        this.regimenhistory = regimenhistory;
        this.chroniccare = chroniccare;
        this.tbscreenhistory = tbscreenhistory;
        this.dmscreenhistory = dmscreenhistory;
        this.anc = anc;
        this.delivery = delivery;
        this.maternalfollowup = maternalfollowup;
        this.child = child;
        this.childfollowup = childfollowup;
        this.partnerinformation = partnerinformation;
        this.nigqual = nigqual;
        this.specimen = specimen;
        this.eid = eid;
        this.labno = labno;
        this.eac = eac;
        this.monitor = monitor;
        this.export = export;
        this.assessment = assessment;
        this.hts = hts;
        this.indexcontact = indexcontact;
        this.encounter = encounter;
        this.drugtherapy = drugtherapy;
        this.mhtc = mhtc;
        this.appointment = appointment;
    }

 

    public Long getExchangeId() {
        return this.exchangeId;
    }

    public void setExchangeId(Long exchangeId) {
        this.exchangeId = exchangeId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getPatient() {
        return this.patient;
    }

    public void setPatient(Date patient) {
        this.patient = patient;
    }

    public Date getClinic() {
        return this.clinic;
    }

    public void setClinic(Date clinic) {
        this.clinic = clinic;
    }

    public Date getPharmacy() {
        return this.pharmacy;
    }

    public void setPharmacy(Date pharmacy) {
        this.pharmacy = pharmacy;
    }

    public Date getLaboratory() {
        return this.laboratory;
    }

    public void setLaboratory(Date laboratory) {
        this.laboratory = laboratory;
    }

    public Date getAdrhistory() {
        return this.adrhistory;
    }

    public void setAdrhistory(Date adrhistory) {
        this.adrhistory = adrhistory;
    }

    public Date getOihistory() {
        return this.oihistory;
    }

    public void setOihistory(Date oihistory) {
        this.oihistory = oihistory;
    }

    public Date getAdherehistory() {
        return this.adherehistory;
    }

    public void setAdherehistory(Date adherehistory) {
        this.adherehistory = adherehistory;
    }

    public Date getStatushistory() {
        return this.statushistory;
    }

    public void setStatushistory(Date statushistory) {
        this.statushistory = statushistory;
    }

    public Date getRegimenhistory() {
        return this.regimenhistory;
    }

    public void setRegimenhistory(Date regimenhistory) {
        this.regimenhistory = regimenhistory;
    }

    public void setChroniccare(Date chroniccare) {
        this.chroniccare = chroniccare;
    }

    public void setTbscreenhistory(Date tbscreenhistory) {
        this.tbscreenhistory = tbscreenhistory;
    }

    public void setDmscreenhistory(Date dmscreenhistory) {
        this.dmscreenhistory = dmscreenhistory;
    }

    public Date getMonitor() {
        return this.monitor;
    }

    public void setMonitor(Date monitor) {
        this.monitor = monitor;
    }

    public Date getExport() {
        return this.export;
    }

    public void setExport(Date export) {
        this.export = export;
    }

    /**
     * @return the chroniccare
     */
    public Date getChroniccare() {
        return chroniccare;
    }

    /**
     * @return the tbscreenhistory
     */
    public Date getTbscreenhistory() {
        return tbscreenhistory;
    }

    /**
     * @return the dmscreenhistory
     */
    public Date getDmscreenhistory() {
        return dmscreenhistory;
    }

    /**
     * @return the anc
     */
    public Date getAnc() {
        return anc;
    }

    /**
     * @param anc the anc to set
     */
    public void setAnc(Date anc) {
        this.anc = anc;
    }

    /**
     * @return the delivery
     */
    public Date getDelivery() {
        return delivery;
    }

    /**
     * @param delivery the delivery to set
     */
    public void setDelivery(Date delivery) {
        this.delivery = delivery;
    }

    /**
     * @return the maternalfollowup
     */
    public Date getMaternalfollowup() {
        return maternalfollowup;
    }

    /**
     * @param maternalfollowup the maternalfollowup to set
     */
    public void setMaternalfollowup(Date maternalfollowup) {
        this.maternalfollowup = maternalfollowup;
    }

    /**
     * @return the child
     */
    public Date getChild() {
        return child;
    }

    /**
     * @param child the child to set
     */
    public void setChild(Date child) {
        this.child = child;
    }

    /**
     * @return the childfollowup
     */
    public Date getChildfollowup() {
        return childfollowup;
    }

    /**
     * @param childfollowup the childfollowup to set
     */
    public void setChildfollowup(Date childfollowup) {
        this.childfollowup = childfollowup;
    }

    /**
     * @return the partnerinformation
     */
    public Date getPartnerinformation() {
        return partnerinformation;
    }

    /**
     * @param partnerinformation the partnerinformation to set
     */
    public void setPartnerinformation(Date partnerinformation) {
        this.partnerinformation = partnerinformation;
    }

    /**
     * @return the nigqual
     */
    public Date getNigqual() {
        return nigqual;
    }

    /**
     * @param nigqual the nigqual to set
     */
    public void setNigqual(Date nigqual) {
        this.nigqual = nigqual;
    }

    /**
     * @return the specimen
     */
    public Date getSpecimen() {
        return specimen;
    }

    /**
     * @param specimen the specimen to set
     */
    public void setSpecimen(Date specimen) {
        this.specimen = specimen;
    }

    /**
     * @return the eid
     */
    public Date getEid() {
        return eid;
    }

    /**
     * @param eid the eid to set
     */
    public void setEid(Date eid) {
        this.eid = eid;
    }

    /**
     * @return the labno
     */
    public Date getLabno() {
        return labno;
    }

    /**
     * @param labno the labno to set
     */
    public void setLabno(Date labno) {
        this.labno = labno;
    }

    /**
     * @param eac the eac to set
     */
    public void setEac(Date eac) {
        this.eac = eac;
    }

    /**
     * @return the assessment
     */
    public Date getAssessment() {
        return assessment;
    }

    /**
     * @param assessment the assessment to set
     */
    public void setAssessment(Date assessment) {
        this.assessment = assessment;
    }

    /**
     * @return the hts
     */
    public Date getHts() {
        return hts;
    }

    /**
     * @param hts the hts to set
     */
    public void setHts(Date hts) {
        this.hts = hts;
    }

    /**
     * @return the indexcontact
     */
    public Date getIndexcontact() {
        return indexcontact;
    }

    /**
     * @param indexcontact the indexcontact to set
     */
    public void setIndexcontact(Date indexcontact) {
        this.indexcontact = indexcontact;
    }

    /**
     * @return the encounter
     */
    public Date getEncounter() {
        return encounter;
    }

    /**
     * @param encounter the encounter to set
     */
    public void setEncounter(Date encounter) {
        this.encounter = encounter;
    }

    /**
     * @return the drugtherapy
     */
    public Date getDrugtherapy() {
        return drugtherapy;
    }

    /**
     * @param drugtherapy the drugtherapy to set
     */
    public void setDrugtherapy(Date drugtherapy) {
        this.drugtherapy = drugtherapy;
    }

    /**
     * @return the mhtc
     */
    public Date getMhtc() {
        return mhtc;
    }

    /**
     * @param mhtc the mhtc to set
     */
    public void setMhtc(Date mhtc) {
        this.mhtc = mhtc;
    }

    /**
     * @return the appointment
     */
    public Date getAppointment() {
        return appointment;
    }

    /**
     * @param appointment the appointment to set
     */
    public void setAppointment(Date appointment) {
        this.appointment = appointment;
    }

}
