package org.fhi360.lamis.model;
// Generated Feb 5, 2019 4:59:21 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Indicatorvalue generated by hbm2java
 */
public class Indicatorvalue  implements java.io.Serializable {


    private long indicatorvalueId;
    private long dataElementId;
    private long categoryId;
    private long stateId;
    private long lgaId;
    private long facilityId;
    private Date reportDate;
    private Integer value;

    public Indicatorvalue() {
    }

    
    public Indicatorvalue(long indicatorvalueId, long dataElementId, long categoryId, long stateId, long lgaId, long facilityId, Date reportDate, Integer value) {
        this.indicatorvalueId = indicatorvalueId;
        this.dataElementId = dataElementId;
        this.categoryId = categoryId;
        this.stateId = stateId;
        this.lgaId = lgaId;
        this.facilityId = facilityId;
        this.reportDate = reportDate;
        this.value = value;
    }

    public long getIndicatorvalueId() {
        return indicatorvalueId;
    }

    public void setIndicatorvalueId(long indicatorvalueId) {
        this.indicatorvalueId = indicatorvalueId;
    }

    public long getDataElementId() {
        return dataElementId;
    }

    public void setDataElementId(long dataElementId) {
        this.dataElementId = dataElementId;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    public long getStateId() {
        return stateId;
    }

    public void setStateId(long stateId) {
        this.stateId = stateId;
    }

    public long getLgaId() {
        return lgaId;
    }

    public void setLgaId(long lgaId) {
        this.lgaId = lgaId;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }
    
    
    
}


