package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private long itemId;
     private String description;
     private String unitMeasure;
     private Integer maxLevel;
     private Integer minLevel;
     private Date dateLastReceived;
     private Date dateLastIssued;
     private Date dateLastAudited;
     private String balanceType;
     private Double unitCost;
     private Integer balance;
     private Date timeStamp;

    public Item() {
    }

	
    public Item(long itemId, String description) {
        this.itemId = itemId;
        this.description = description;
    }
    public Item(long itemId, String description, String unitMeasure, Integer maxLevel, Integer minLevel, Date dateLastReceived, Date dateLastIssued, Date dateLastAudited, String balanceType, Double unitCost, Integer balance, Date timeStamp) {
       this.itemId = itemId;
       this.description = description;
       this.unitMeasure = unitMeasure;
       this.maxLevel = maxLevel;
       this.minLevel = minLevel;
       this.dateLastReceived = dateLastReceived;
       this.dateLastIssued = dateLastIssued;
       this.dateLastAudited = dateLastAudited;
       this.balanceType = balanceType;
       this.unitCost = unitCost;
       this.balance = balance;
       this.timeStamp = timeStamp;
    }
   
    public long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(long itemId) {
        this.itemId = itemId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUnitMeasure() {
        return this.unitMeasure;
    }
    
    public void setUnitMeasure(String unitMeasure) {
        this.unitMeasure = unitMeasure;
    }
    public Integer getMaxLevel() {
        return this.maxLevel;
    }
    
    public void setMaxLevel(Integer maxLevel) {
        this.maxLevel = maxLevel;
    }
    public Integer getMinLevel() {
        return this.minLevel;
    }
    
    public void setMinLevel(Integer minLevel) {
        this.minLevel = minLevel;
    }
    public Date getDateLastReceived() {
        return this.dateLastReceived;
    }
    
    public void setDateLastReceived(Date dateLastReceived) {
        this.dateLastReceived = dateLastReceived;
    }
    public Date getDateLastIssued() {
        return this.dateLastIssued;
    }
    
    public void setDateLastIssued(Date dateLastIssued) {
        this.dateLastIssued = dateLastIssued;
    }
    public Date getDateLastAudited() {
        return this.dateLastAudited;
    }
    
    public void setDateLastAudited(Date dateLastAudited) {
        this.dateLastAudited = dateLastAudited;
    }
    public String getBalanceType() {
        return this.balanceType;
    }
    
    public void setBalanceType(String balanceType) {
        this.balanceType = balanceType;
    }
    public Double getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(Double unitCost) {
        this.unitCost = unitCost;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }




}


