package org.fhi360.lamis.model;
// Generated Oct 15, 2014 11:39:23 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Labno generated by hbm2java
 */
public class Labno implements java.io.Serializable {

    private long labnoId;
    private long facilityId;
    private Integer year;
    private Integer lastno;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;


    public Labno() {
    }

    public Labno(long labnoId, long facilityId) {
        this.labnoId = labnoId;
        this.facilityId = facilityId;
    }

    public Labno(long labnoId, long facilityId, Integer year, Integer lastno, Date timeStamp, Integer uploaded, Date timeUploaded) {
        this.labnoId = labnoId;
        this.facilityId = facilityId;
        this.year = year;
        this.lastno = lastno;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
    }

   

    public long getLabnoId() {
        return this.labnoId;
    }

    public void setLabnoId(long labnoId) {
        this.labnoId = labnoId;
    }

    public Integer getYear() {
        return this.year;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getLastno() {
        return this.lastno;
    }

    public void setLastno(Integer lastno) {
        this.lastno = lastno;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

}
