package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Laboratory generated by hbm2java
 */
public class Laboratory implements java.io.Serializable {

    private long laboratoryId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private Date dateReported;
    private Date dateCollected;
    private String labno;
    private String resultab;
    private String resultpc;
    private String comment;
    private long labtestId;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
     private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    
    public Laboratory() {
    }

    public Laboratory(long laboratoryId, Patient patient, long facilityId, Date dateReported, long labtestId) {
        this.laboratoryId = laboratoryId;
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateReported = dateReported;
        this.labtestId = labtestId;
    }

    public Laboratory(long laboratoryId, Patient patient, long patientId, long facilityId, Date dateReported, Date dateCollected, String labno, String resultab, String resultpc, String comment, long labtestId, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.laboratoryId = laboratoryId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.dateReported = dateReported;
        this.dateCollected = dateCollected;
        this.labno = labno;
        this.resultab = resultab;
        this.resultpc = resultpc;
        this.comment = comment;
        this.labtestId = labtestId;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

  

   

    public long getLaboratoryId() {
        return this.laboratoryId;
    }

    public void setLaboratoryId(long laboratoryId) {
        this.laboratoryId = laboratoryId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateReported() {
        return this.dateReported;
    }

    public void setDateReported(Date dateReported) {
        this.dateReported = dateReported;
    }

    public Date getDateCollected() {
        return this.dateCollected;
    }

    public void setDateCollected(Date dateCollected) {
        this.dateCollected = dateCollected;
    }

    public String getLabno() {
        return this.labno;
    }

    public void setLabno(String labno) {
        this.labno = labno;
    }

    public String getResultab() {
        return this.resultab;
    }

    public void setResultab(String resultab) {
        this.resultab = resultab;
    }

    public String getResultpc() {
        return this.resultpc;
    }

    public void setResultpc(String resultpc) {
        this.resultpc = resultpc;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public long getLabtestId() {
        return this.labtestId;
    }

    public void setLabtestId(long labtestId) {
        this.labtestId = labtestId;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
