package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

/**
 * Labtest generated by hbm2java
 */
public class Labtest implements java.io.Serializable {

    private long labtestId;
    private Labtestcategory labtestcategory;
    private String description;
    private String measureab;
    private String measurepc;

    public Labtest() {
    }

    public Labtest(long labtestId, Labtestcategory labtestcategory, String description) {
        this.labtestId = labtestId;
        this.labtestcategory = labtestcategory;
        this.description = description;
    }

    public Labtest(long labtestId, Labtestcategory labtestcategory, String description, String measureab, String measurepc) {
        this.labtestId = labtestId;
        this.labtestcategory = labtestcategory;
        this.description = description;
        this.measureab = measureab;
        this.measurepc = measurepc;
    }

    public long getLabtestId() {
        return this.labtestId;
    }

    public void setLabtestId(long labtestId) {
        this.labtestId = labtestId;
    }

    public Labtestcategory getLabtestcategory() {
        return this.labtestcategory;
    }

    public void setLabtestcategory(Labtestcategory labtestcategory) {
        this.labtestcategory = labtestcategory;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMeasureab() {
        return this.measureab;
    }

    public void setMeasureab(String measureab) {
        this.measureab = measureab;
    }

    public String getMeasurepc() {
        return this.measurepc;
    }

    public void setMeasurepc(String measurepc) {
        this.measurepc = measurepc;
    }

}
