package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Lga generated by hbm2java
 */
public class Lga  implements java.io.Serializable {


     private long lgaId;
     private State state;
     private String name;
     private Set<Facility> facilities = new HashSet<Facility>(0);

    public Lga() {
    }

	
    public Lga(long lgaId, State state, String name) {
        this.lgaId = lgaId;
        this.state = state;
        this.name = name;
    }
    public Lga(long lgaId, State state, String name, Set<Facility> facilities) {
       this.lgaId = lgaId;
       this.state = state;
       this.name = name;
       this.facilities = facilities;
    }
   
    public long getLgaId() {
        return this.lgaId;
    }
    
    public void setLgaId(long lgaId) {
        this.lgaId = lgaId;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Facility> getFacilities() {
        return this.facilities;
    }
    
    public void setFacilities(Set<Facility> facilities) {
        this.facilities = facilities;
    }




}


