package org.fhi360.lamis.model;
// Generated 19-Jul-2014 19:48:23 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Maternalfollowup generated by hbm2java
 */
public class Maternalfollowup implements java.io.Serializable {

    private long maternalfollowupId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private long ancId;
    private Date dateVisit;
    private Double bodyWeight;
    private String bp;
    private Double fundalHeight;
    private String fetalPresentation;
    private Date dateConfirmedHiv;
    private String timeHivDiagnosis;
    private String arvRegimenPast;
    private String typeOfVisit;
    private String tbStatus;
    private String visitStatus;
    private String gestationalAge;
    private String arvRegimenCurrent;
    private Date dateArvRegimenCurrent;
    private String viralLoadCollected;
    private Date dateSampleCollected;
    private Integer screenPostPartum;
    private String cd4Ordered;
    private Double cd4;
    private Integer counselNutrition;
    private Integer counselFeeding;
    private Integer counselFamilyPlanning;
    private String familyPlanningMethod;
    private String referred;
    private Date dateNextVisit;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Maternalfollowup() {
    }

    public Maternalfollowup(Patient patient, long facilityId, Date dateVisit) {
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
    }

    public Maternalfollowup(long maternalfollowupId, Patient patient, long patientId, long facilityId, long ancId, Date dateVisit, Double bodyWeight, String bp, Double fundalHeight, String fetalPresentation, Date dateConfirmedHiv, String timeHivDiagnosis, String arvRegimenPast, String typeOfVisit, String tbStatus, String visitStatus, String gestationalAge, String arvRegimenCurrent, Date dateArvRegimenCurrent, String viralLoadCollected, Date dateSampleCollected, Integer screenPostPartum, String cd4Ordered, Double cd4, Integer counselNutrition, Integer counselFeeding, Integer counselFamilyPlanning, String familyPlanningMethod, String referred, Date dateNextVisit, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.maternalfollowupId = maternalfollowupId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.ancId = ancId;
        this.dateVisit = dateVisit;
        this.bodyWeight = bodyWeight;
        this.bp = bp;
        this.fundalHeight = fundalHeight;
        this.fetalPresentation = fetalPresentation;
        this.dateConfirmedHiv = dateConfirmedHiv;
        this.timeHivDiagnosis = timeHivDiagnosis;
        this.arvRegimenPast = arvRegimenPast;
        this.typeOfVisit = typeOfVisit;
        this.tbStatus = tbStatus;
        this.visitStatus = visitStatus;
        this.gestationalAge = gestationalAge;
        this.arvRegimenCurrent = arvRegimenCurrent;
        this.dateArvRegimenCurrent = dateArvRegimenCurrent;
        this.viralLoadCollected = viralLoadCollected;
        this.dateSampleCollected = dateSampleCollected;
        this.screenPostPartum = screenPostPartum;
        this.cd4Ordered = cd4Ordered;
        this.cd4 = cd4;
        this.counselNutrition = counselNutrition;
        this.counselFeeding = counselFeeding;
        this.counselFamilyPlanning = counselFamilyPlanning;
        this.familyPlanningMethod = familyPlanningMethod;
        this.referred = referred;
        this.dateNextVisit = dateNextVisit;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

    public long getMaternalfollowupId() {
        return maternalfollowupId;
    }

    public void setMaternalfollowupId(long maternalfollowupId) {
        this.maternalfollowupId = maternalfollowupId;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public long getAncId() {
        return ancId;
    }

    public void setAncId(long ancId) {
        this.ancId = ancId;
    }

    public Date getDateVisit() {
        return dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public Double getBodyWeight() {
        return bodyWeight;
    }

    public void setBodyWeight(Double bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    public String getBp() {
        return bp;
    }

    public void setBp(String bp) {
        this.bp = bp;
    }

    public Double getFundalHeight() {
        return fundalHeight;
    }

    public void setFundalHeight(Double fundalHeight) {
        this.fundalHeight = fundalHeight;
    }

    public String getFetalPresentation() {
        return fetalPresentation;
    }

    public void setFetalPresentation(String fetalPresentation) {
        this.fetalPresentation = fetalPresentation;
    }

    public Date getDateConfirmedHiv() {
        return dateConfirmedHiv;
    }

    public void setDateConfirmedHiv(Date dateConfirmedHiv) {
        this.dateConfirmedHiv = dateConfirmedHiv;
    }

    public String getTimeHivDiagnosis() {
        return timeHivDiagnosis;
    }

    public void setTimeHivDiagnosis(String timeHivDiagnosis) {
        this.timeHivDiagnosis = timeHivDiagnosis;
    }

    public String getArvRegimenPast() {
        return arvRegimenPast;
    }

    public void setArvRegimenPast(String arvRegimenPast) {
        this.arvRegimenPast = arvRegimenPast;
    }

    public String getTypeOfVisit() {
        return typeOfVisit;
    }

    public void setTypeOfVisit(String typeOfVisit) {
        this.typeOfVisit = typeOfVisit;
    }

    public String getTbStatus() {
        return tbStatus;
    }

    public void setTbStatus(String tbStatus) {
        this.tbStatus = tbStatus;
    }

    public String getVisitStatus() {
        return visitStatus;
    }

    public void setVisitStatus(String visitStatus) {
        this.visitStatus = visitStatus;
    }

    public String getGestationalAge() {
        return gestationalAge;
    }

    public void setGestationalAge(String gestationalAge) {
        this.gestationalAge = gestationalAge;
    }

    public String getArvRegimenCurrent() {
        return arvRegimenCurrent;
    }

    public void setArvRegimenCurrent(String arvRegimenCurrent) {
        this.arvRegimenCurrent = arvRegimenCurrent;
    }

    public Date getDateArvRegimenCurrent() {
        return dateArvRegimenCurrent;
    }

    public void setDateArvRegimenCurrent(Date dateArvRegimenCurrent) {
        this.dateArvRegimenCurrent = dateArvRegimenCurrent;
    }

    public String getViralLoadCollected() {
        return viralLoadCollected;
    }

    public void setViralLoadCollected(String viralLoadCollected) {
        this.viralLoadCollected = viralLoadCollected;
    }

    public Date getDateSampleCollected() {
        return dateSampleCollected;
    }

    public void setDateSampleCollected(Date dateSampleCollected) {
        this.dateSampleCollected = dateSampleCollected;
    }

    public Integer getScreenPostPartum() {
        return screenPostPartum;
    }

    public void setScreenPostPartum(Integer screenPostPartum) {
        this.screenPostPartum = screenPostPartum;
    }

    public String getCd4Ordered() {
        return cd4Ordered;
    }

    public void setCd4Ordered(String cd4Ordered) {
        this.cd4Ordered = cd4Ordered;
    }

    public Double getCd4() {
        return cd4;
    }

    public void setCd4(Double cd4) {
        this.cd4 = cd4;
    }

    public Integer getCounselNutrition() {
        return counselNutrition;
    }

    public void setCounselNutrition(Integer counselNutrition) {
        this.counselNutrition = counselNutrition;
    }

    public Integer getCounselFeeding() {
        return counselFeeding;
    }

    public void setCounselFeeding(Integer counselFeeding) {
        this.counselFeeding = counselFeeding;
    }

    public Integer getCounselFamilyPlanning() {
        return counselFamilyPlanning;
    }

    public void setCounselFamilyPlanning(Integer counselFamilyPlanning) {
        this.counselFamilyPlanning = counselFamilyPlanning;
    }

    public String getFamilyPlanningMethod() {
        return familyPlanningMethod;
    }

    public void setFamilyPlanningMethod(String familyPlanningMethod) {
        this.familyPlanningMethod = familyPlanningMethod;
    }

    public String getReferred() {
        return referred;
    }

    public void setReferred(String referred) {
        this.referred = referred;
    }

    public Date getDateNextVisit() {
        return dateNextVisit;
    }

    public void setDateNextVisit(Date dateNextVisit) {
        this.dateNextVisit = dateNextVisit;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
