package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private long messageId;
     private Integer messageType;
     private Integer daysToAppointment;
     private Date dateToSend;
     private String recipients;
     private String message1;
     private String message2;
     private String message3;
     private String message4;

    public Message() {
    }

	
    public Message(long messageId) {
        this.messageId = messageId;
    }

    public Message(long messageId, Integer messageType) {
        this.messageId = messageId;
        this.messageType = messageType;
    }
    
    public Message(long messageId, Integer messageType, Integer daysToAppointment, Date dateToSend, String recipients, String message1, String message2, String message3, String message4) {
       this.messageId = messageId;
       this.messageType = messageType;
       this.daysToAppointment = daysToAppointment;
       this.dateToSend = dateToSend;
       this.recipients = recipients;
       this.message1 = message1;
       this.message2 = message2;
       this.message3 = message3;
       this.message4 = message4;
    }

    /**
     * @return the messageId
     */
    public long getMessageId() {
        return messageId;
    }

    /**
     * @param messageId the messageId to set
     */
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }

    /**
     * @return the messageType
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * @param messageType the messageType to set
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * @return the recipients
     */
    public String getRecipients() {
        return recipients;
    }

    /**
     * @param message1 the recipients to set
     */
    public void setRecipients(String recipients) {
        this.recipients = recipients;
    }

    /**
     * @return the message1
     */
    public String getMessage1() {
        return message1;
    }

    /**
     * @param message1 the message1 to set
     */
    public void setMessage1(String message1) {
        this.message1 = message1;
    }

    /**
     * @return the message2
     */
    public String getMessage2() {
        return message2;
    }

    /**
     * @param message2 the message2 to set
     */
    public void setMessage2(String message2) {
        this.message2 = message2;
    }

    /**
     * @return the message3
     */
    public String getMessage3() {
        return message3;
    }

    /**
     * @param message3 the message3 to set
     */
    public void setMessage3(String message3) {
        this.message3 = message3;
    }

    /**
     * @return the message4
     */
    public String getMessage4() {
        return message4;
    }

    /**
     * @param message4 the message4 to set
     */
    public void setMessage4(String message4) {
        this.message4 = message4;
    }

    /**
     * @return the daysToAppointment
     */
    public Integer getDaysToAppointment() {
        return daysToAppointment;
    }

    /**
     * @param daysToAppointment the daysToAppointment to set
     */
    public void setDaysToAppointment(Integer daysToAppointment) {
        this.daysToAppointment = daysToAppointment;
    }

    /**
     * @return the dateToSend
     */
    public Date getDateToSend() {
        return dateToSend;
    }

    /**
     * @param dateToSend the dateToSend to set
     */
    public void setDateToSend(Date dateToSend) {
        this.dateToSend = dateToSend;
    }
   
}


