package org.fhi360.lamis.model;
//  Generated 24-Aug-2014 20:34:11 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partnerinformation generated by hbm2java
 */
public class Partnerinformation implements java.io.Serializable {

    private long partnerinformationId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private long ancId;
    private Date dateVisit;
    private String partnerNotification;
    private String partnerHivStatus;
    private String partnerReferred;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
    private Set patients = new HashSet(0);
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Partnerinformation() {
    }

    public Partnerinformation(Patient patient, long facilityId, Date dateVisit) {
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
    }

    public Partnerinformation(long partnerinformationId, Patient patient, long patientId, long facilityId, long ancId, Date dateVisit, String partnerNotification, String partnerHivStatus, String partnerReferred, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.partnerinformationId = partnerinformationId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.ancId = ancId;
        this.dateVisit = dateVisit;
        this.partnerNotification = partnerNotification;
        this.partnerHivStatus = partnerHivStatus;
        this.partnerReferred = partnerReferred;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

    

    public long getPartnerinformationId() {
        return this.partnerinformationId;
    }

    public void setPartnerinformationId(long partnerinformationId) {
        this.partnerinformationId = partnerinformationId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return this.dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public String getPartnerNotification() {
        return this.partnerNotification;
    }

    public void setPartnerNotification(String partnerNotification) {
        this.partnerNotification = partnerNotification;
    }

    public String getPartnerHivStatus() {
        return this.partnerHivStatus;
    }

    public void setPartnerHivStatus(String partnerHivStatus) {
        this.partnerHivStatus = partnerHivStatus;
    }

    public String getPartnerReferred() {
        return this.partnerReferred;
    }

    public void setPartnerReferred(String partnerReferred) {
        this.partnerReferred = partnerReferred;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Set getPatients() {
        return this.patients;
    }

    public void setPatients(Set patients) {
        this.patients = patients;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    public long getAncId() {
        return ancId;
    }

    public void setAncId(long ancId) {
        this.ancId = ancId;
    }

    
}
