package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Performance generated by hbm2java
 */
public class Performance  implements java.io.Serializable {


     private long performanceId;
     private Integer year;
     private Integer month;
     private Integer denominator;
     private Integer numerator;
     private Integer indicatorId;
     private Integer facilityId;

    public Performance() {
    }

	
    public Performance(long performanceId) {
        this.performanceId = performanceId;
    }
    public Performance(long performanceId, Integer year, Integer month, Integer denominator, Integer numerator, Integer indicatorId, Integer facilityId) {
       this.performanceId = performanceId;
       this.year = year;
       this.month = month;
       this.denominator = denominator;
       this.numerator = numerator;
       this.indicatorId = indicatorId;
       this.facilityId = facilityId;
    }
   
    public long getPerformanceId() {
        return this.performanceId;
    }
    
    public void setPerformanceId(long performanceId) {
        this.performanceId = performanceId;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getDenominator() {
        return this.denominator;
    }
    
    public void setDenominator(Integer denominator) {
        this.denominator = denominator;
    }
    public Integer getNumerator() {
        return this.numerator;
    }
    
    public void setNumerator(Integer numerator) {
        this.numerator = numerator;
    }
    public Integer getIndicatorId() {
        return this.indicatorId;
    }
    
    public void setIndicatorId(Integer indicatorId) {
        this.indicatorId = indicatorId;
    }
    public Integer getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }




}


