package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Pharmacy generated by hbm2java
 */
public class Pharmacy implements java.io.Serializable {

    private long pharmacyId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private Date dateVisit;
    private Integer duration;
    private Double morning;
    private Double afternoon;
    private Double evening;
    private String adrScreened;
    private String adrIds;
    private String dmocType;
    private Integer prescripError;
    private Integer adherence;
    private Date nextAppointment;
    private long regimentypeId;
    private long regimenId;
    private long regimendrugId;
    private Date timeStamp;
    private Long userId;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Pharmacy() {
    }

    public Pharmacy(long pharmacyId, Patient patient, long facilityId, Date dateVisit, long regimentypeId, long regimenId, long regimendrugId) {
        this.pharmacyId = pharmacyId;
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.regimentypeId = regimentypeId;
        this.regimenId = regimenId;
        this.regimendrugId = regimendrugId;
    }

    public Pharmacy(long pharmacyId, Patient patient, long patientId, long facilityId, Date dateVisit, Integer duration, Double morning, Double afternoon, Double evening, String adrScreened, String adrIds, String dmocType, Integer prescripError, Integer adherence, Date nextAppointment, long regimentypeId, long regimenId, long regimendrugId, Date timeStamp, Long userId, Integer uploaded, Date timeUploaded, String uuid) {
        this.pharmacyId = pharmacyId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.duration = duration;
        this.morning = morning;
        this.afternoon = afternoon;
        this.evening = evening;
        this.adrScreened = adrScreened;
        this.adrIds = adrIds;
        this.dmocType = dmocType;
        this.prescripError = prescripError;
        this.adherence = adherence;
        this.nextAppointment = nextAppointment;
        this.regimentypeId = regimentypeId;
        this.regimenId = regimenId;
        this.regimendrugId = regimendrugId;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

    public long getPharmacyId() {
        return pharmacyId;
    }

    public void setPharmacyId(long pharmacyId) {
        this.pharmacyId = pharmacyId;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Double getMorning() {
        return morning;
    }

    public void setMorning(Double morning) {
        this.morning = morning;
    }

    public Double getAfternoon() {
        return afternoon;
    }

    public void setAfternoon(Double afternoon) {
        this.afternoon = afternoon;
    }

    public Double getEvening() {
        return evening;
    }

    public void setEvening(Double evening) {
        this.evening = evening;
    }

    public String getAdrScreened() {
        return adrScreened;
    }

    public void setAdrScreened(String adrScreened) {
        this.adrScreened = adrScreened;
    }

    public String getAdrIds() {
        return adrIds;
    }

    public void setAdrIds(String adrIds) {
        this.adrIds = adrIds;
    }

    public String getDmocType() {
        return dmocType;
    }

    public void setDmocType(String dmocType) {
        this.dmocType = dmocType;
    }

    public Integer getPrescripError() {
        return prescripError;
    }

    public void setPrescripError(Integer prescripError) {
        this.prescripError = prescripError;
    }

    public Integer getAdherence() {
        return adherence;
    }

    public void setAdherence(Integer adherence) {
        this.adherence = adherence;
    }

    public Date getNextAppointment() {
        return nextAppointment;
    }

    public void setNextAppointment(Date nextAppointment) {
        this.nextAppointment = nextAppointment;
    }

    public long getRegimentypeId() {
        return regimentypeId;
    }

    public void setRegimentypeId(long regimentypeId) {
        this.regimentypeId = regimentypeId;
    }

    public long getRegimenId() {
        return regimenId;
    }

    public void setRegimenId(long regimenId) {
        this.regimenId = regimenId;
    }

    public long getRegimendrugId() {
        return regimendrugId;
    }

    public void setRegimendrugId(long regimendrugId) {
        this.regimendrugId = regimendrugId;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    

}
