package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private long privilegeId;
     private String description;
     private Set<Userprivilege> userprivileges = new HashSet<Userprivilege>(0);

    public Privilege() {
    }

	
    public Privilege(long privilegeId, String description) {
        this.privilegeId = privilegeId;
        this.description = description;
    }
    public Privilege(long privilegeId, String description, Set<Userprivilege> userprivileges) {
       this.privilegeId = privilegeId;
       this.description = description;
       this.userprivileges = userprivileges;
    }
   
    public long getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(long privilegeId) {
        this.privilegeId = privilegeId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Userprivilege> getUserprivileges() {
        return this.userprivileges;
    }
    
    public void setUserprivileges(Set<Userprivilege> userprivileges) {
        this.userprivileges = userprivileges;
    }




}


