package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Regimendrug generated by hbm2java
 */
public class Regimendrug  implements java.io.Serializable {


     private long regimendrugId;
     private Drug drug;
     private Regimen regimen;

    public Regimendrug() {
    }

    public Regimendrug(long regimendrugId, Drug drug, Regimen regimen) {
       this.regimendrugId = regimendrugId;
       this.drug = drug;
       this.regimen = regimen;
    }
   
    public long getRegimendrugId() {
        return this.regimendrugId;
    }
    
    public void setRegimendrugId(long regimendrugId) {
        this.regimendrugId = regimendrugId;
    }
    public Drug getDrug() {
        return this.drug;
    }
    
    public void setDrug(Drug drug) {
        this.drug = drug;
    }
    public Regimen getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(Regimen regimen) {
        this.regimen = regimen;
    }




}


