package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Regimenhistory generated by hbm2java
 */
public class Regimenhistory implements java.io.Serializable {

    private long historyId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private Date dateVisit;
    private String regimentype;
    private String regimen;
    private String reasonSwitchedSubs;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
     private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

   
    public Regimenhistory() {
    }

    public Regimenhistory(long historyId, Patient patient, long facilityId, Date dateVisit) {
        this.historyId = historyId;
        this.patient = patient;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
    }

    public Regimenhistory(long historyId, Patient patient, long patientId, long facilityId, Date dateVisit, String regimentype, String regimen, String reasonSwitchedSubs, Date timeStamp, Integer uploaded, Date timeUploaded, String uuid) {
        this.historyId = historyId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.dateVisit = dateVisit;
        this.regimentype = regimentype;
        this.regimen = regimen;
        this.reasonSwitchedSubs = reasonSwitchedSubs;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

   

    public long getHistoryId() {
        return this.historyId;
    }

    public void setHistoryId(long historyId) {
        this.historyId = historyId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public Date getDateVisit() {
        return this.dateVisit;
    }

    public void setDateVisit(Date dateVisit) {
        this.dateVisit = dateVisit;
    }

    public String getRegimentype() {
        return this.regimentype;
    }

    public void setRegimentype(String regimentype) {
        this.regimentype = regimentype;
    }

    public String getRegimen() {
        return this.regimen;
    }

    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the reasonSwitchedSubs
     */
    public String getReasonSwitchedSubs() {
        return reasonSwitchedSubs;
    }

    /**
     * @param reasonSwitchedSubs the reasonSwitchedSubs to set
     */
    public void setReasonSwitchedSubs(String reasonSwitchedSubs) {
        this.reasonSwitchedSubs = reasonSwitchedSubs;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
