package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private long scheduleId;
     private Facility facility;
     private Integer monday;
     private Integer tuesday;
     private Integer wednesday;
     private Integer thursday;
     private Integer friday;
     private Integer saturday;
     private Integer sunday;
     private String service;

    public Schedule() {
    }

	
    public Schedule(long scheduleId, Facility facility) {
        this.scheduleId = scheduleId;
        this.facility = facility;
    }
    public Schedule(long scheduleId, Facility facility, Integer monday, Integer tuesday, Integer wednesday, Integer thursday, Integer friday, Integer saturday, Integer sunday, String service) {
       this.scheduleId = scheduleId;
       this.facility = facility;
       this.monday = monday;
       this.tuesday = tuesday;
       this.wednesday = wednesday;
       this.thursday = thursday;
       this.friday = friday;
       this.saturday = saturday;
       this.sunday = sunday;
       this.service = service;
    }
   
    public long getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(long scheduleId) {
        this.scheduleId = scheduleId;
    }
    public Facility getFacility() {
        return this.facility;
    }
    
    public void setFacility(Facility facility) {
        this.facility = facility;
    }
    public Integer getMonday() {
        return this.monday;
    }
    
    public void setMonday(Integer monday) {
        this.monday = monday;
    }
    public Integer getTuesday() {
        return this.tuesday;
    }
    
    public void setTuesday(Integer tuesday) {
        this.tuesday = tuesday;
    }
    public Integer getWednesday() {
        return this.wednesday;
    }
    
    public void setWednesday(Integer wednesday) {
        this.wednesday = wednesday;
    }
    public Integer getThursday() {
        return this.thursday;
    }
    
    public void setThursday(Integer thursday) {
        this.thursday = thursday;
    }
    public Integer getFriday() {
        return this.friday;
    }
    
    public void setFriday(Integer friday) {
        this.friday = friday;
    }
    public Integer getSaturday() {
        return this.saturday;
    }
    
    public void setSaturday(Integer saturday) {
        this.saturday = saturday;
    }
    public Integer getSunday() {
        return this.sunday;
    }
    
    public void setSunday(Integer sunday) {
        this.sunday = sunday;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }




}


