package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sent generated by hbm2java
 */
public class Sent  implements java.io.Serializable {


     private long sentId;
     private String phone;
     private String message;
     private Date timeStamp;

    public Sent() {
    }

	
    public Sent(long sentId, String phone, String message) {
        this.sentId = sentId;
        this.phone = phone;
        this.message = message;
    }
    public Sent(long sentId, String phone, String message, Date timeStamp) {
       this.sentId = sentId;
       this.phone = phone;
       this.message = message;
       this.timeStamp = timeStamp;
    }
   
    public long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(long sentId) {
        this.sentId = sentId;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }


}


