package org.fhi360.lamis.model;
// Generated Oct 16, 2014 12:09:06 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Specimen generated by hbm2java
 */
public class Specimen implements java.io.Serializable {

    private long specimenId;
    private long facilityId;
    private long stateId;
    private long lgaId;
    private long treatmentUnitId;
    private String specimenType;
    private String labno;
    private String barcode;
    private Date dateReceived;
    private Date dateCollected;
    private Date dateAssay;
    private Date dateReported;
    private Date dateDispatched;
    private Integer qualityCntrl;
    private String result;
    private String reasonNoTest;
    private String hospitalNum;
    private String surname;
    private String otherNames;
    private String gender;
    private Date dateBirth;
    private Integer age;
    private String ageUnit;
    private String address;
    private String phone;
    private Long userId;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    public Specimen() {
    }

    public Specimen(long specimenId, long facilityId, long stateId, long lgaId, long treatmentUnitId, String specimenType, String labno, Date dateReceived) {
        this.specimenId = specimenId;
        this.facilityId = facilityId;
        this.stateId = stateId;
        this.lgaId = lgaId;
        this.treatmentUnitId = treatmentUnitId;
        this.specimenType = specimenType;
        this.labno = labno;
        this.dateReceived = dateReceived;
    }

    public Specimen(long specimenId, long facilityId, long stateId, long lgaId, long treatmentUnitId, String specimenType, String labno, String barcode, Date dateReceived, Date dateCollected, Date dateAssay, Date dateReported, Date dateDispatched, Integer qualityCntrl, String result, String reasonNoTest, String hospitalNum, String surname, String otherNames, String gender, Date dateBirth, Integer age, String ageUnit, String address, String phone, Long userId, Date timeStamp, Integer uploaded, Date timeUploaded, String uuid) {
        this.specimenId = specimenId;
        this.facilityId = facilityId;
        this.stateId = stateId;
        this.lgaId = lgaId;
        this.treatmentUnitId = treatmentUnitId;
        this.specimenType = specimenType;
        this.labno = labno;
        this.barcode = barcode;
        this.dateReceived = dateReceived;
        this.dateCollected = dateCollected;
        this.dateAssay = dateAssay;
        this.dateReported = dateReported;
        this.dateDispatched = dateDispatched;
        this.qualityCntrl = qualityCntrl;
        this.result = result;
        this.reasonNoTest = reasonNoTest;
        this.hospitalNum = hospitalNum;
        this.surname = surname;
        this.otherNames = otherNames;
        this.gender = gender;
        this.dateBirth = dateBirth;
        this.age = age;
        this.ageUnit = ageUnit;
        this.address = address;
        this.phone = phone;
        this.userId = userId;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }

    public long getSpecimenId() {
        return this.specimenId;
    }

    public void setSpecimenId(long specimenId) {
        this.specimenId = specimenId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public long getStateId() {
        return stateId;
    }

    public void setStateId(long stateId) {
        this.stateId = stateId;
    }

    public long getLgaId() {
        return lgaId;
    }

    public void setLgaId(long lgaId) {
        this.lgaId = lgaId;
    }

    public long getTreatmentUnitId() {
        return treatmentUnitId;
    }

    public void setTreatmentUnitId(long treatmentUnitId) {
        this.treatmentUnitId = treatmentUnitId;
    }

    public String getSpecimenType() {
        return this.specimenType;
    }

    public void setSpecimenType(String specimenType) {
        this.specimenType = specimenType;
    }

    public String getLabno() {
        return this.labno;
    }

    public void setLabno(String labno) {
        this.labno = labno;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public Date getDateReceived() {
        return this.dateReceived;
    }

    public void setDateReceived(Date dateReceived) {
        this.dateReceived = dateReceived;
    }

    public Date getDateCollected() {
        return this.dateCollected;
    }

    public void setDateCollected(Date dateCollected) {
        this.dateCollected = dateCollected;
    }

    public Date getDateAssay() {
        return this.dateAssay;
    }

    public void setDateAssay(Date dateAssay) {
        this.dateAssay = dateAssay;
    }

    public Date getDateReported() {
        return this.dateReported;
    }

    public void setDateReported(Date dateReported) {
        this.dateReported = dateReported;
    }

    public Date getDateDispatched() {
        return this.dateDispatched;
    }

    public void setDateDispatched(Date dateDispatched) {
        this.dateDispatched = dateDispatched;
    }

    public Integer getQualityCntrl() {
        return qualityCntrl;
    }

    public void setQualityCntrl(Integer qualityCntrl) {
        this.qualityCntrl = qualityCntrl;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getReasonNoTest() {
        return this.reasonNoTest;
    }

    public void setReasonNoTest(String reasonNoTest) {
        this.reasonNoTest = reasonNoTest;
    }

    public String getHospitalNum() {
        return this.hospitalNum;
    }

    public void setHospitalNum(String hospitalNum) {
        this.hospitalNum = hospitalNum;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getOtherNames() {
        return this.otherNames;
    }

    public void setOtherNames(String otherNames) {
        this.otherNames = otherNames;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getDateBirth() {
        return this.dateBirth;
    }

    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAgeUnit() {
        return this.ageUnit;
    }

    public void setAgeUnit(String ageUnit) {
        this.ageUnit = ageUnit;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

}
