package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private long statusId;
     private String description;
     private Integer groupNum;

    public Status() {
    }

	
    public Status(long statusId) {
        this.statusId = statusId;
    }
    public Status(long statusId, String description, Integer groupNum) {
       this.statusId = statusId;
       this.description = description;
       this.groupNum = groupNum;
    }
   
    public long getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(long statusId) {
        this.statusId = statusId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getGroupNum() {
        return this.groupNum;
    }
    
    public void setGroupNum(Integer groupNum) {
        this.groupNum = groupNum;
    }




}


