package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private long stateId;
     private String name;
     private Set<Lga> lgas = new HashSet<Lga>(0);

    public State() {
    }

	
    public State(long stateId, String name) {
        this.stateId = stateId;
        this.name = name;
    }
    public State(long stateId, String name, Set<Lga> lgas) {
       this.stateId = stateId;
       this.name = name;
       this.lgas = lgas;
    }
   
    public long getStateId() {
        return this.stateId;
    }
    
    public void setStateId(long stateId) {
        this.stateId = stateId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Lga> getLgas() {
        return this.lgas;
    }
    
    public void setLgas(Set<Lga> lgas) {
        this.lgas = lgas;
    }




}


