package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Statushistory generated by hbm2java
 */
public class Statushistory implements java.io.Serializable {

    private long historyId;
    private Patient patient;
    private long patientId;
    private long facilityId;
    private String currentStatus;
    private Date dateCurrentStatus;
    private String reasonInterrupt;
    private String causeDeath;
    private Date dateTracked;
    private String outcome;
    private Date agreedDate;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
      private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    
    public Statushistory() {
    }

    public Statushistory(long historyId, Patient patient, long facilityId) {
        this.historyId = historyId;
        this.patient = patient;
        this.facilityId = facilityId;
    }

    public Statushistory(long historyId, Patient patient, long patientId, long facilityId, String currentStatus, Date dateCurrentStatus, String reasonInterrupt, String causeDeath, Date dateTracked, String outcome, Date agreedDate, Date timeStamp, Integer uploaded, Date timeUploaded, String uuid) {
        this.historyId = historyId;
        this.patient = patient;
        this.patientId = patientId;
        this.facilityId = facilityId;
        this.currentStatus = currentStatus;
        this.dateCurrentStatus = dateCurrentStatus;
        this.reasonInterrupt = reasonInterrupt;
        this.causeDeath = causeDeath;
        this.dateTracked = dateTracked;
        this.outcome = outcome;
        this.agreedDate = agreedDate;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.uuid = uuid;
    }


    public long getHistoryId() {
        return this.historyId;
    }

    public void setHistoryId(long historyId) {
        this.historyId = historyId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public long getPatientId() {
        return patientId;
    }

    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    public long getFacilityId() {
        return this.facilityId;
    }

    public void setFacilityId(long facilityId) {
        this.facilityId = facilityId;
    }

    public String getCurrentStatus() {
        return this.currentStatus;
    }

    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public Date getDateCurrentStatus() {
        return this.dateCurrentStatus;
    }

    public void setDateCurrentStatus(Date dateCurrentStatus) {
        this.dateCurrentStatus = dateCurrentStatus;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * @return the uploaded
     */
    public Integer getUploaded() {
        return uploaded;
    }

    /**
     * @param uploaded the uploaded to set
     */
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * @return the timeUploaded
     */
    public Date getTimeUploaded() {
        return timeUploaded;
    }

    /**
     * @param timeUploaded the timeUploaded to set
     */
    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    /**
     * @return the reasonInterrupt
     */
    public String getReasonInterrupt() {
        return reasonInterrupt;
    }

    /**
     * @param reasonInterrupt the reasonInterrupt to set
     */
    public void setReasonInterrupt(String reasonInterrupt) {
        this.reasonInterrupt = reasonInterrupt;
    }

    /**
     * @return the causeDeath
     */
    public String getCauseDeath() {
        return causeDeath;
    }

    /**
     * @param causeDeath the causeDeath to set
     */
    public void setCauseDeath(String causeDeath) {
        this.causeDeath = causeDeath;
    }

    /**
     * @return the dateTracked
     */
    public Date getDateTracked() {
        return dateTracked;
    }

    /**
     * @param dateTracked the dateTracked to set
     */
    public void setDateTracked(Date dateTracked) {
        this.dateTracked = dateTracked;
    }

    /**
     * @return the outcome
     */
    public String getOutcome() {
        return outcome;
    }

    /**
     * @param outcome the outcome to set
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * @return the agreedDate
     */
    public Date getAgreedDate() {
        return agreedDate;
    }

    /**
     * @param agreedDate the agreedDate to set
     */
    public void setAgreedDate(Date agreedDate) {
        this.agreedDate = agreedDate;
    }

    @Override
    public String toString() {
        return "Statushistory{" + "historyId=" + historyId + ", patientId=" + patientId + ", facilityId=" + facilityId + ", currentStatus=" + currentStatus + ", dateCurrentStatus=" + dateCurrentStatus + ", reasonInterrupt=" + reasonInterrupt + ", causeDeath=" + causeDeath + ", dateTracked=" + dateTracked + ", outcome=" + outcome + ", agreedDate=" + agreedDate + ", timeStamp=" + timeStamp + ", uploaded=" + uploaded + ", timeUploaded=" + timeUploaded + ", uuid=" + uuid + '}';
    }
    
}
