package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Adhere generated by hbm2java
 */
public class Tbscreen  implements java.io.Serializable {


     private long tbscreenId;
     private String description;

    public Tbscreen() {
    }

    public Tbscreen(long tbscreenId, String description) {
       this.tbscreenId = tbscreenId;
       this.description = description;
    }
   
    public long getTbscreenId() {
        return this.tbscreenId;
    }
    
    public void setTbscreenId(long tbscreenId) {
        this.tbscreenId = tbscreenId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


