package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private long userId;
    private String username;
    private String password;
    private String fullname;
    private Long facilityId;
    private Long localId;
    private Date timeLogin;
    private Integer viewIdentifier;
    private String userGroup;
    private Date timeStamp;
    private Integer uploaded;
    private Date timeUploaded;
    private String stateIds;
    private Set<Userprivilege> userprivileges = new HashSet<>(0);
    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public User() {
    }

    public User(long userId, String username, String password, String userGroup) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.userGroup = userGroup;
    }

    public User(long userId, String username, String password, String fullname, Long facilityId, Long localId, Date timeLogin, Integer viewIdentifier, String userGroup, Date timeStamp, Integer uploaded, Date timeUploaded, String stateIds, String uuid) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.facilityId = facilityId;
        this.localId = localId;
        this.timeLogin = timeLogin;
        this.viewIdentifier = viewIdentifier;
        this.userGroup = userGroup;
        this.timeStamp = timeStamp;
        this.uploaded = uploaded;
        this.timeUploaded = timeUploaded;
        this.stateIds = stateIds;
        this.uuid = uuid;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public Long getFacilityId() {
        return facilityId;
    }

    public void setFacilityId(Long facilityId) {
        this.facilityId = facilityId;
    }

    public Long getLocalId() {
        return localId;
    }

    public void setLocalId(Long localId) {
        this.localId = localId;
    }

    public Date getTimeLogin() {
        return timeLogin;
    }

    public void setTimeLogin(Date timeLogin) {
        this.timeLogin = timeLogin;
    }

    public Integer getViewIdentifier() {
        return viewIdentifier;
    }

    public void setViewIdentifier(Integer viewIdentifier) {
        this.viewIdentifier = viewIdentifier;
    }

    public String getStateIds() {
        return stateIds;
    }

    public void setStateIds(String stateIds) {
        this.stateIds = stateIds;
    }

    public String getUserGroup() {
        return userGroup;
    }

    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Integer getUploaded() {
        return uploaded;
    }

    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }

    public Date getTimeUploaded() {
        return timeUploaded;
    }

    public void setTimeUploaded(Date timeUploaded) {
        this.timeUploaded = timeUploaded;
    }

    public Set<Userprivilege> getUserprivileges() {
        return userprivileges;
    }

    public void setUserprivileges(Set<Userprivilege> userprivileges) {
        this.userprivileges = userprivileges;
    }

    @Override
    public String toString() {
        return "User{" + "userId=" + userId + ", username=" + username + ", password=" + password + ", fullname=" + fullname + ", facilityId=" + facilityId + ", localId=" + localId + ", timeLogin=" + timeLogin + ", viewIdentifier=" + viewIdentifier + ", stateIds=" + stateIds + ", userGroup=" + userGroup + ", timeStamp=" + timeStamp + ", uploaded=" + uploaded + ", timeUploaded=" + timeUploaded + ", userprivileges=" + userprivileges + '}';
    }

}
