package org.fhi360.lamis.model;
// Generated Feb 16, 2013 8:46:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Userprivilege generated by hbm2java
 */
public class Userprivilege  implements java.io.Serializable {


     private long userprivilegeId;
     private User user;
     private Privilege privilege;

    public Userprivilege() {
    }

    public Userprivilege(long userprivilegeId, User user, Privilege privilege) {
       this.userprivilegeId = userprivilegeId;
       this.user = user;
       this.privilege = privilege;
    }
   
    public long getUserprivilegeId() {
        return this.userprivilegeId;
    }
    
    public void setUserprivilegeId(long userprivilegeId) {
        this.userprivilegeId = userprivilegeId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }




}


